agent-ovs/lib/include/opflexagent/test/ModbFixture.h, agent-ovs/ovs/FlowUtils.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp
This reverts commit 38bc9a134322cd0c5ce1c63338b17ed91442caaa.
=> Revert "Add flow-rules to support ICMP type/code in L24Classifier"

agent-ovs/lib/include/opflexagent/test/ModbFixture.h, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/FlowUtils.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/include/FlowUtils.h, agent-ovs/ovs/test/IntFlowManager_test.cpp
This reverts commit d05f3ab2bd19fd0c2f6c26d5c3f0dc86d31aaeb0.
=> Revert "Issue when we create bi-directional contract."

agent-ovs/configure.ac
Enable prometheus support by default
=> Enable prometheus integration by default

agent-ovs/cmd/test/policy_repo_stress.cpp, agent-ovs/lib/EndpointManager.cpp, agent-ovs/ovs/Packets.cpp
=> Address some more coverity warnings

agent-ovs/lib/NetFlowManager.cpp, agent-ovs/lib/include/opflexagent/NetFlowManager.h, agent-ovs/ovs/JsonRpc.cpp, agent-ovs/ovs/NetFlowRenderer.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/include/JsonRpc.h, agent-ovs/ovs/include/NetFlowRenderer.h, agent-ovs/ovs/test/SpanRenderer_test.cpp
Refactor to have a common getUuid from OVSDB table
Remove some includes/logs
=> Refactor to have a common getUuid from OVSDB table

agent-ovs/lib/EndpointManager.cpp, agent-ovs/lib/FSWatcher.cpp, agent-ovs/lib/PolicyManager.cpp, agent-ovs/ovs/FlowExecutor.cpp, agent-ovs/ovs/Packets.cpp
Safety checks for null termination of inotify events
=> Coverity fixes

.travis.yml, .travis/asan-build.sh, .travis/install-dependencies.sh, .travis/travis-build.sh, .travis/tsan-build.sh
https://travis-ci.org/github/noironetworks/opflex/builds/687674147
=> Optimizing travis build times by using cached ovs and prometheus debs

libopflex/modb/ObjectInstance.cpp
=> Address ASAN issue exposed by recently added UT

agent-ovs/lib/SpanManager.cpp, agent-ovs/lib/include/opflexagent/SpanManager.h, agent-ovs/ovs/test/SpanRenderer_test.cpp, agent-ovs/ovs/test/include/MockRpcConnection.h
=> Minor improvements to ERSPAN code/UTs

agent-ovs/lib/test/EndpointManager_test.cpp, libopflex/ofcore/OFFramework.cpp
=> Fix tsan issues related to "data race on vptr"

.travis.yml, .travis/ubsan-build.sh
=> enabling ubsan in travis build matrix

lgtm.yml
=> LGTM Fix missing line

libopflex/comms/ActivePeer.cpp, libopflex/comms/CommunicationPeer.cpp, libopflex/comms/active_connection.cpp, libopflex/comms/common.cpp, libopflex/comms/include/Makefile.am, libopflex/comms/include/yajr/rpc/methods.hpp, libopflex/comms/include/yajr/transport/ZeroCopyOpenSSL.hpp, libopflex/comms/loopdata.cpp, libopflex/comms/passive_listener.cpp, libopflex/comms/peer.cpp, libopflex/comms/rpc.cpp, libopflex/comms/rpc/message/factory/inboundmessage.cpp, libopflex/comms/test/comms_test.cpp, libopflex/comms/transport/PlainText.cpp, libopflex/comms/transport/ZeroCopyOpenSSL.cpp, libopflex/engine/OpflexHandler.cpp, libopflex/logging/include/opflex/logging/internal/logging.hpp
=> Convert all VLOG calls to LOG

agent-ovs/lib/Agent.cpp, agent-ovs/lib/NetFlowManager.cpp, agent-ovs/lib/SpanManager.cpp, agent-ovs/lib/include/opflexagent/SpanSessionState.h, agent-ovs/lib/include/opflexagent/cmd.h, libopflex/comms/CommunicationPeer.cpp, libopflex/include/opflex/modb/ConstInfo.h, libopflex/include/opflex/modb/EnumInfo.h, libopflex/include/opflex/modb/PropertyInfo.h, libopflex/include/opflex/yajr/internal/comms.hpp, libopflex/include/opflex/yajr/rpc/rpc.hpp, libopflex/modb/EnumInfo.cpp
=> Address some of the LGTM complaints

agent-ovs/ovs/include/PacketDecoder.h
=> Fix LGTM issue

agent-ovs/ovs/JsonRpc.cpp, agent-ovs/ovs/JsonRpcRenderer.cpp, agent-ovs/ovs/include/JsonRpc.h
This code will eventually be completely rewritten
but want to try to keep the TSAN runs clean
=> Address TSAN issue in JSONRPC code

genie/src/main/java/org/opendaylight/opflex/genie/engine/file/Lister.java, genie/src/main/java/org/opendaylight/opflex/genie/engine/model/Cat.java, genie/src/main/java/org/opendaylight/opflex/genie/engine/model/RelatorCat.java, genie/src/main/java/org/opendaylight/opflex/genie/engine/parse/modlan/Node.java, genie/src/main/java/org/opendaylight/opflex/modlan/parse/TransitionTable.java
=> Address a few of the coverity complaints in genie

agent-ovs/ovs/AccessFlowManager.cpp, libopflex/comms/active_connection.cpp
=> Address a few more LGTM complaints

agent-ovs/ovs/test/IntFlowManager_test.cpp
=> Adding prometheus UT for remoteep

agent-ovs/ovs/JsonRpc.cpp, agent-ovs/ovs/include/JsonRpc.h
Widen the lock around all access to the response payload
=> Address TSAN issue in ERSPAN code

agent-ovs/lib/PrometheusManager.cpp, agent-ovs/lib/include/opflexagent/PrometheusManager.h, agent-ovs/ovs/PolicyStatsManager.cpp, agent-ovs/ovs/test/ContractStatsManager_test.cpp
- stop relying on observer mo, and directly update stats
- prom ut support for peer stats
=> Ofpeer stats cleanup and add promeetheus ut

agent-ovs/lib/AgentLogHandler.cpp, agent-ovs/lib/logging.cpp, libopflex/comms/test/comms_test.cpp, libopflex/include/opflex/logging/OFLogHandler.h, libopflex/logging/include/opflex/logging/internal/logging.hpp
=> Remove DEBUG5 log level

agent-ovs/ovs/JsonRpcTransactMessage.cpp, agent-ovs/ovs/include/JsonRpcTransactMessage.h, agent-ovs/ovs/test/MockRpcConnection.cpp, libopflex/include/opflex/rpc/JsonRpcMessage.h, libopflex/include/opflex/yajr/rpc/message_factory.hpp, libopflex/include/opflex/yajr/rpc/rpc.hpp
Minor refactorings preparing for monitor support
=> Remove clone from JSONRPC messages

agent-ovs/ovs/JsonRpcTransactMessage.cpp, agent-ovs/ovs/include/JsonRpcTransactMessage.h, agent-ovs/ovs/test/MockRpcConnection.cpp, agent-ovs/ovs/test/include/MockRpcConnection.h, libopflex/comms/CommunicationPeer.cpp, libopflex/comms/include/yajr/rpc/gen/echo.hpp, libopflex/engine/GbpOpflexServer.cpp, libopflex/engine/InspectorClientImpl.cpp, libopflex/engine/InspectorServerHandler.cpp, libopflex/engine/OpflexHandler.cpp, libopflex/engine/OpflexMessage.cpp, libopflex/engine/OpflexPEHandler.cpp, libopflex/engine/OpflexServerHandler.cpp, libopflex/engine/include/opflex/engine/internal/OpflexConnection.h, libopflex/engine/include/opflex/engine/internal/OpflexMessage.h, libopflex/engine/include/opflex/engine/internal/ProcessorMessage.h, libopflex/include/opflex/rpc/JsonRpcMessage.h, libopflex/include/opflex/yajr/rpc/rpc.hpp
Minor changes to message interface as part of rework
=> Make serializePayload and operator() const

libopflex/comms/active_connection.cpp
=> Address lgtm "function declared inside block"

agent-ovs/lib/PolicyManager.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/TableState.cpp, libopflex/comms/ActiveTcpPeer.cpp, libopflex/comms/ActiveUnixPeer.cpp
- Overloaded assignment does not return 'this'
- Use of integer where enum is preferred
- Function declared in block
=> address few more lgtm issues

agent-ovs/lib/include/opflexagent/SpanSessionState.h, agent-ovs/ovs/JsonRpc.cpp, agent-ovs/ovs/include/JsonRpcTransactMessage.h
Add assignment operator impl when providing copy constructor
=> Addressing LGTM complaints

agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/include/JsonRpc.h, agent-ovs/ovs/include/JsonRpcTransactMessage.h, agent-ovs/ovs/include/OvsdbConnection.h, libopflex/comms/rpc/message/factory/inboundmessage.cpp, libopflex/engine/OpflexHandler.cpp, libopflex/include/opflex/rpc/JsonRpcConnection.h
Address another LGTM issue in JsonRpcTransactMessage
=> Report OVSDB transaction errors and log

agent-ovs/Makefile.am, agent-ovs/ovs/JsonRpc.cpp, agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/OvsdbMessage.cpp, agent-ovs/ovs/OvsdbTransactMessage.cpp, agent-ovs/ovs/include/OvsdbConnection.h, agent-ovs/ovs/include/OvsdbMessage.h, agent-ovs/ovs/include/OvsdbTransactMessage.h, agent-ovs/ovs/test/MockRpcConnection.cpp, agent-ovs/ovs/test/include/MockRpcConnection.h
Rename JsonRpcTransactMessage to OvsdbTransactMessage
=> Introduce OvsdbMessage abstract class

agent-ovs/ovs/include/AccessFlowManager.h
=> address tsan warnings in access flow manager tests

agent-ovs/ovs/include/OvsdbTransactMessage.h
=> Address another LGTM issue

agent-ovs/lib/NotifServer.cpp, agent-ovs/lib/test/IdGenerator_test.cpp, agent-ovs/lib/test/NotifServer_test.cpp, agent-ovs/ovs/SwitchManager.cpp
=> coverty: addressing unchecked return values

libopflex/engine/OpflexConnection.cpp, libopflex/ofcore/OFFramework.cpp
=> lgtm: address virtual-call-in-constructor/destructor warnings

agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/include/OvsdbConnection.h, libopflex/Makefile.am, libopflex/comms/Makefile.am, libopflex/comms/rpc/JsonRpcConnection.cpp, libopflex/comms/rpc/JsonRpcHandler.cpp, libopflex/engine/OpflexConnection.cpp, libopflex/engine/OpflexHandler.cpp, libopflex/engine/include/opflex/engine/internal/OpflexConnection.h, libopflex/engine/include/opflex/engine/internal/OpflexHandler.h, libopflex/engine/include/opflex/engine/internal/OpflexMessage.h, libopflex/include/opflex/rpc/JsonRpcConnection.h, libopflex/include/opflex/rpc/JsonRpcHandler.h, libopflex/include/opflex/rpc/JsonRpcMessage.h
Pulling code out of opflex specific classes into generic jsonrpc classes that will be used for ovsdb communication as well
=> Rework opflex comms to share more with ovsdb comms

agent-ovs/lib/IdGenerator.cpp
=> coverty: addressing invalid iterator usage

agent-ovs/cmd/gbp_inspect.cpp, agent-ovs/cmd/mcast_daemon.cpp, agent-ovs/cmd/test/policy_repo_stress.cpp, agent-ovs/lib/Agent.cpp, agent-ovs/lib/SimStats.cpp, agent-ovs/ovs/SwitchManager.cpp
=> addressing a few coverty exception handling warnings

agent-ovs/ovs/Packets.cpp, agent-ovs/ovs/test/ServiceStatsManager_test.cpp
=> More coverity fixes

docs/prometheus.md
=> Changing "tree" to "blob" to display raw image file in prometheus.md

agent-ovs/cmd/test/policy_repo_stress.cpp, agent-ovs/lib/MulticastListener.cpp, agent-ovs/lib/NotifServer.cpp
=> Coverity exception errors

agent-ovs/lib/FSWatcher.cpp
=> addressing coverty warnings

agent-ovs/lib/NotifServer.cpp
=> Coverity exception fix

agent-ovs/ovs/AdvertManager.cpp, agent-ovs/ovs/PolicyStatsManager.cpp
=> More coverity exception fixes

agent-ovs/ovs/AdvertManager.cpp
=> addressing coverity exception

agent-ovs/cmd/test/GbpClient.cpp
=> Address coverity complaint by initializing member in constructor

agent-ovs/Makefile.am
=> Add missing header needed for RPM/DEB builds

agent-ovs/cmd/test/GbpClient.cpp
=> Fix incorrect coverity fix

agent-ovs/cmd/test/mock_server.cpp
=> Fix problems during indus cherry-pick of CSCvu46192/SR689109894

libopflex/engine/test/Processor_test.cpp
=> CSCvu46192/SR689109894: adding ut to remove stale peer connections

agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/OvsdbMonitorMessage.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/include/OvsdbConnection.h, agent-ovs/ovs/include/OvsdbMessage.h, agent-ovs/ovs/include/OvsdbMonitorMessage.h, agent-ovs/ovs/include/OvsdbState.h, agent-ovs/ovs/test/include/MockRpcConnection.h, libopflex/comms/rpc/JsonRpcConnection.cpp
Add OVSDB update support
Filter columns used by monitor command
Use cached bridge UUID in ERSPAN commands
Various updates
=> Add OVSDB update support

libopflex/engine/test/Makefile.am
=> Linking engine_test with pthread lib to fix rpm builds

agent-ovs/ovs/JsonRpc.cpp, agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/OvsdbTransactMessage.cpp, agent-ovs/ovs/include/OvsdbMessage.h, agent-ovs/ovs/include/OvsdbState.h, agent-ovs/ovs/include/OvsdbTransactMessage.h, agent-ovs/ovs/test/NetFlowRenderer_test.cpp, agent-ovs/ovs/test/SpanRenderer_test.cpp
Populate array types in local store
=> Rename TupleData/TupleDataSet to OvsdbValue/OvsdbValues

libopflex/ofcore/test/Makefile.am
=> Linking ofcore_test with pthread lib to fix rpm builds

libopflex/cwrapper/test/Makefile.am
=> Linking cwrapper_test with pthread lib to fix rpm builds

.travis/coveralls-deploy.sh
=> Piping coverall logs to /dev/null

agent-ovs/Makefile.am, agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/include/OvsdbConnection.h, agent-ovs/ovs/test/OvsdbConnection_test.cpp
Add UTs for OVSDB monitor/update handling
Add mock responses to exercise parsing code
=> Add UTs for OVSDB monitor/update handling

libopflex/cwrapper/test/Makefile.am, libopflex/engine/OpflexPool.cpp, libopflex/engine/test/Makefile.am, libopflex/ofcore/test/Makefile.am
Fix cherry-pick issues in indus
=> Indus cherry pick

agent-ovs/cmd/test/opflex_server.cpp, libopflex/cwrapper/test/Makefile.am, libopflex/engine/OpflexPool.cpp, libopflex/engine/test/Makefile.am, libopflex/ofcore/test/Makefile.am
Manually cherry-pick Gautams changes that disappeared since my commit.
=> Jordan cherry pick

genie/MODEL/SPECIFIC/OBSERVER/modbcounts.mdl, genie/MODEL/SPECIFIC/OBSERVER/total.mdl
=> Model changes to house total active count of a few MOs

agent-ovs/lib/include/opflexagent/Snat.h
Remove unused unset* APIs from Snat
=> Remove unused unset* APIs from Snat

agent-ovs/grafana/Peer.json
=> Adding unresolved policy count dashboard in grafana

libopflex/comms/loopdata.cpp
=> Protecting peer list with mutex

agent-ovs/Makefile.am, agent-ovs/lib/test/SnatManager_test.cpp
Added SnatManager_test.cpp with tests for FSSnatSource creation/deletion. Increased coverage to 86.5%. 
Isuue #1170
=> Basic UTs for Snat functionality

libopflex/engine/include/opflex/engine/internal/OpflexPool.h, libopflex/include/opflex/modb/MAC.h, libopflex/include/opflex/modb/URI.h, libopflex/include/opflex/modb/mo-internal/ObjectInstance.h, libopflex/modb/URI.cpp
=> Remove checks for older cpp versions

agent-ovs/lib/test/SnatManager_test.cpp
=> Add a few more checks to SNAT UTs to increase coverage

libopflex/cwrapper/test/cwrapper_test.cpp
=> Increase UT coverage in cwrapper code

agent-ovs/lib/test/ExtraConfigManager_test.cpp
=> Add basic test of droplog cfg parsing

agent-ovs/lib/test/ExtraConfigManager_test.cpp
=> DropLogConfig test

agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/include/OVSRenderer.h, agent-ovs/ovs/include/PacketLogHandler.h
TODO: Add ports to droplogs and more re-org
=> Move droplogger to a thread

agent-ovs/lib/SpanManager.cpp, agent-ovs/ovs/NetFlowRenderer.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/test/NetFlowRenderer_test.cpp, agent-ovs/ovs/test/SpanRenderer_test.cpp
Ensure that L2Ep.interfaceName is set if used as src
Cleanup a few logs
=> Update span tests slightly

agent-ovs/lib/test/ServiceManager_test.cpp
Unit Tests for FSServiceSource to increase coverage.
=> UTs for Service

agent-ovs/lib/test/EndpointManager_test.cpp
=> Add tests of EP file params not already covered by other tests

libopflex/engine/include/opflex/engine/internal/MOSerializer.h, libopflex/engine/test/MOSerialize_test.cpp
Fix issue in JSON generated from serializeUnresolved
Add call from UT for this functionality
=> Fix issue in JSON generated from serializeUnresolved

agent-ovs/lib/Agent.cpp, agent-ovs/lib/include/opflexagent/Endpoint.h, agent-ovs/lib/include/opflexagent/Service.h, agent-ovs/lib/include/opflexagent/SpanSessionState.h, agent-ovs/lib/test/EndpointManager_test.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/include/OvsdbState.h
Set erspan_dir when creating interface
Cleanup some clang-tidy complaints
=> Set erspan_dir when creating interface

lgtm.yml
=> Backport LGTM build config to jordan branch

.travis.yml
=> Since we dont have 50min time limit in travis.com, enabling ubsan build

agent-ovs/ovs/include/OvsdbConnection.h, libopflex/engine/OpflexPool.cpp, libopflex/engine/Processor.cpp, libopflex/include/opflex/util/ThreadManager.h, libopflex/modb/URIQueue.cpp
=> Addressing coverity complaints

libopflex/engine/test/MOSerialize_test.cpp
=> Add UTs for updateMOs method used by opflex server

agent-ovs/lib/SpanManager.cpp, agent-ovs/lib/include/opflexagent/SpanSessionState.h, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/include/OvsdbState.h, agent-ovs/ovs/include/SpanRenderer.h, agent-ovs/ovs/test/SpanRenderer_test.cpp
=> Populate ERSPAN session ID from passed policy

agent-ovs/lib/include/opflexagent/PrometheusManager.h, agent-ovs/lib/test/ServiceManager_test.cpp
- check service-mode as local_anycast instead of LB
- clang-tidy fix
- fix alignment
=> fix service mode check in service manager tests

agent-ovs/ovs/JsonRpcRenderer.cpp, agent-ovs/ovs/NetFlowRenderer.cpp, agent-ovs/ovs/OvsdbTransactMessage.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/include/JsonRpcRenderer.h, agent-ovs/ovs/include/NetFlowRenderer.h, agent-ovs/ovs/include/OvsdbMessage.h, agent-ovs/ovs/include/SpanRenderer.h, agent-ovs/ovs/test/IntFlowManager_test.cpp
Fix abort if agent is shutdown with pending OVSDB tasks
Remove some noisy logs
Address clang-tidy complaints
Add basic tests of a couple of functions
=> Fix abort if agent is shutdown with pending OVSDB tasks

agent-ovs/configure.ac, agent-ovs/debian/control, agent-ovs/debian/rules.in, agent-ovs/lib/Agent.cpp, agent-ovs/lib/EndpointManager.cpp, agent-ovs/lib/PrometheusManager.cpp, agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/TableDropStatsManager.cpp, agent-ovs/ovs/include/AccessFlowManager.h, agent-ovs/ovs/test/TableDropStatsManager_test.cpp, agent-ovs/rpm/opflex-agent.spec.in
cherry-pick some fixes that seem to have disappeared after the previous mishap I had with cherry-picking into Jordan. I thought it only missed 3 but looks like there were several more. I did not merge 
https://github.com/noironetworks/opflex/commit/75a20a358800dd559e6a58dfa40d6f6109eb2bd7
since it was giving me merge conflicts. If its important I would appreciate if Gautam can take care of that change.
Thanks.
=> Jordan missing

genie/src/main/java/org/opendaylight/opflex/genie/content/format/agent/meta/cpp/FMetaDef.java, genie/src/main/java/org/opendaylight/opflex/genie/content/format/proxy/meta/cpp/FMetaDef.java, genie/src/main/java/org/opendaylight/opflex/genie/content/format/proxy/structure/cpp/FClassDef.java, genie/src/main/java/org/opendaylight/opflex/genie/content/model/mrelator/MRelationship.java, genie/src/main/java/org/opendaylight/opflex/genie/content/model/mrelator/MRelator.java, genie/src/main/java/org/opendaylight/opflex/genie/content/parse/preference/PToNode.java, libopflex/engine/Processor.cpp, libopflex/include/opflex/modb/ClassInfo.h
Resolver and reverse relationship classes were never implemented/used
=> Reduce amount of code generated by genie

agent-ovs/ovs/OvsdbMessage.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/include/SpanRenderer.h, agent-ovs/ovs/test/SpanRenderer_test.cpp
Update mirror in place if it already exists
=> Reworking erspan output port handling to support updates

agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/include/SpanRenderer.h, agent-ovs/ovs/test/SpanRenderer_test.cpp
=> Add a couple of additional UTs

.travis.yml, .travis/asan-build.sh, .travis/install-dependencies.sh, .travis/travis-build.sh, .travis/tsan-build.sh, .travis/ubsan-build.sh
=> Enable grpc in travis build matrix and cache grpc

agent-ovs/ovs/test/SpanRenderer_test.cpp
=> Increase coverage in SpanRenderer

.travis/install-dependencies.sh
=> Installing cmake 3.17.0 always, make install looks for presence of cmake

libopflex/engine/OpflexPool.cpp, libopflex/engine/OpflexServerConnection.cpp, libopflex/engine/OpflexServerHandler.cpp
=> Address coverity issues

agent-ovs/lib/EndpointManager.cpp, agent-ovs/lib/FSPacketDropLogConfigSource.cpp, agent-ovs/lib/IdGenerator.cpp, agent-ovs/lib/LearningBridgeIface.cpp, agent-ovs/lib/ModelEndpointSource.cpp, agent-ovs/ovs/PolicyStatsManager.cpp, libopflex/comms/CommunicationPeer.cpp, libopflex/comms/transport/ZeroCopyOpenSSL.cpp
=> Fix some codacity issues

agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/include/IntFlowManager.h, agent-ovs/ovs/test/IntFlowManager_test.cpp
=> Add UTs to increase IntFlowManager coverage

agent-ovs/cmd/test/Policies.cpp, agent-ovs/lib/IdGenerator.cpp, agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/TunnelEpManager.cpp, agent-ovs/ovs/Packets.cpp, agent-ovs/ovs/PolicyStatsManager.cpp, agent-ovs/ovs/ServiceStatsManager.cpp, libopflex/engine/Processor.cpp, libopflex/modb/ObjectStore.cpp, libopflex/ofcore/test/MO_test.cpp
=> Address few more codacity issues

libopflex/modb/ObjectInstance.cpp
=> Address issue uncovered by coverity

agent-ovs/ovs/TableDropStatsManager.cpp
=> Minor fix for crash when br-access is not present

agent-ovs/configure.commit
=> Incorrect githash being returned with version option

agent-ovs/ovs/include/OvsdbConnection.h
=> Addressing TSAN complaint in UT

agent-ovs/configure.commit
=> Incorrect githash being returned with version option (#211)

agent-ovs/ovs/PacketDecoderLayers.cpp, agent-ovs/ovs/include/PacketDecoderLayers.h, agent-ovs/ovs/test/PacketDecoder_test.cpp
Correct print arguments after qtag fix.
=> Fix previous commit

agent-ovs/grafana/Server.json
=> Adding grafana dashboards for opflex-server metrics

agent-ovs/ovs/PacketLogHandler.cpp
=> Prune queueing error-logs in droplogs

agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/PacketLogHandler.cpp
Reduce log level for queue-backup errors in droplog
=> Fix missing TLV in acc-br

agent-ovs/ovs/OVSRenderer.cpp
=> Capture traffic for ERSPAN from br-access instead of br-int

.gitreview
=> Remove no longer used git submodules/review files

agent-ovs/debian/opflex-agent.dirs, agent-ovs/debian/opflex-agent.postinst, agent-ovs/rpm/opflex-agent.spec.in
=> Add missing faults dir from deb/rpm artifacts

agent-ovs/lib/NetFlowManager.cpp, agent-ovs/ovs/NetFlowRenderer.cpp, agent-ovs/ovs/include/NetFlowRenderer.h, agent-ovs/ovs/test/NetFlowRenderer_test.cpp
Generate a unique hash from agent UUID to use for domain ID
Set active flow timeout based on passed policy
=> Set some additional fields when configuring ipfix

agent-ovs/lib/test/EndpointManager_test.cpp
=> Add test of parsing of other supported params in extep files

agent-ovs/ovs/NetFlowRenderer.cpp
=> Sample input traffic only for ipfix

agent-ovs/ovs/NetFlowRenderer.cpp, agent-ovs/ovs/OvsdbTransactMessage.cpp
=> Fix overflow in ipfix domain ID

agent-ovs/lib/FSPacketDropLogConfigSource.cpp, agent-ovs/lib/FSWatcher.cpp, agent-ovs/lib/test/ExtraConfigManager_test.cpp
=> Add basic UT for flow based drop logging

agent-ovs/Makefile.am
- make clean should also remove the grpc generated files from cmd/test
=> make clean cmd/test dir

libopflex/engine/InspectorClientImpl.cpp, libopflex/engine/Processor.cpp, libopflex/engine/include/opflex/engine/internal/InspectorServerHandler.h, libopflex/modb/Mutator.cpp
Cleanup a few unneeded includes
=> Remove useless log for observables

agent-ovs/ovs/IntFlowManager.cpp
- when pods onprem access cloud service it will appear as NS to the cloud
- to handle this we need to make sure that before we bounce the packet to
the node, in addition to figuring out the route via remote ep we also
do the service translation.
- in reverse direction the service untranslation needs to happen on the
bouncing node
- the policy will still be applied on the target node so we dont need to
apply policy twice
Here is a summary of the flows so far.
bounce flows only on nodes that do the bounce
BOUNCE_TO_NODE
cookie=0x0, duration=71126.721s, table=12, n_packets=3817, n_bytes=305897, priority=16384,ip,dl_src=00:00:5e:00:52:13,dl_dst=00:22:bd:f8:19:ff,nw_src=50.1.1.0/24 actions=load:0x762b52->NXM_NX_REG3[],write_metadata:0xb/0xff,goto_table:14
cookie=0x0, duration=71126.721s, …
=> Add support for accessing cloud services via CSR

agent-ovs/lib/QosManager.cpp, agent-ovs/lib/include/opflexagent/QosListener.h, agent-ovs/lib/include/opflexagent/QosManager.h, agent-ovs/lib/test/QosManager_test.cpp, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/ActionBuilder.cpp, agent-ovs/ovs/include/AccessFlowManager.h, agent-ovs/ovs/include/ActionBuilder.h, agent-ovs/ovs/include/ovs-shim.h, agent-ovs/ovs/ovs-shim.c, agent-ovs/ovs/test/AccessFlowManager_test.cpp, agent-ovs/ovs/test/include/FlowManagerFixture.h
Created this pull request from a different branch.
=> Handle dscp config in QosManager.

agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/include/IntFlowManager.h, agent-ovs/ovs/test/IntFlowManager_test.cpp, agent-ovs/ovs/test/include/FlowManagerFixture.h
- set knob to disable stats flows by default
- added make check cases to test stats flows for both enabled and disabled cases
=> Disable svc stats flows by default

agent-ovs/configure.ac, agent-ovs/debian/libopflex-agent.shlibs, genie/configs/genie.cfg, genie/pom.xml, genie/src/main/java/org/opendaylight/opflex/genie/content/format/agent/build/automake/cpp/FConfigureAC.java, libopflex/configure.ac
=> Bump version for next release

libopflex/engine/MOSerializer.cpp, libopflex/engine/Processor.cpp
=> Remove a few unhelpful logs

libopflex/engine/MOSerializer.cpp, libopflex/engine/Processor.cpp
Cherry pick https://github.com/noironetworks/opflex/pull/271
=> Remove a few unhelpful logs (#271)

agent-ovs/lib/FSEndpointSource.cpp, agent-ovs/lib/FSExternalEndpointSource.cpp, agent-ovs/lib/include/opflexagent/Endpoint.h, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/include/FlowConstants.h, agent-ovs/ovs/test/AccessFlowManager_test.cpp
This reverts commit e21bcd2dd4efef6a16da3d662a5ecdacd7d447ad.
Apparently they still need them.
=> Revert "Revert openshift hack to dup untagged packets (#266)"

agent-ovs/lib/FSEndpointSource.cpp, agent-ovs/lib/FSExternalEndpointSource.cpp, agent-ovs/lib/include/opflexagent/Endpoint.h, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/include/FlowConstants.h, agent-ovs/ovs/test/AccessFlowManager_test.cpp
This reverts commit e21bcd2dd4efef6a16da3d662a5ecdacd7d447ad.
Apparently they still need them.
=> Revert "Revert openshift hack to dup untagged packets (#266)" (#281)

agent-ovs/lib/QosManager.cpp, agent-ovs/lib/include/opflexagent/QosListener.h, agent-ovs/lib/include/opflexagent/QosManager.h, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/QosRenderer.cpp, agent-ovs/ovs/include/AccessFlowManager.h, agent-ovs/ovs/include/QosRenderer.h
Modb notifications  are processed concurrently. Concurrent tasks are
1. updating cached information
2. programme ovsdb/flows to configure qos
=> Optimize QosManager: increase concurrency.

agent-ovs/ovs/PacketLogHandler.cpp, agent-ovs/ovs/include/PacketDecoder.h, agent-ovs/ovs/test/PacketDecoder_test.cpp
Uninitialized meta fields caused some failed tests.
=> Initialize meta

agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/ServiceManager.cpp, agent-ovs/lib/TaskQueue.cpp, agent-ovs/lib/logging.cpp, agent-ovs/lib/test/FaultManager_test.cpp, agent-ovs/lib/test/PolicyManager_test.cpp, agent-ovs/lib/test/SpanManager_test.cpp, agent-ovs/ovs/FlowReader.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/TableDropStatsManager.cpp, agent-ovs/ovs/TableState.cpp, agent-ovs/ovs/test/MockFlowExecutor.cpp, agent-ovs/ovs/test/TableState_test.cpp
=> Addressing a few codacy and clang-tidy complaints

libopflex/include/opflex/yajr/rpc/rpc.hpp
Remove a couple of unused fields
=> Address compilation issue with Ubuntu 20.10

.travis.yml
=> Reduce usage of travis resources until we have time to move

lgtm.yml
=> Include/Exclude a couple of LGTM checks

agent-ovs/lib/FSLearningBridgeSource.cpp, agent-ovs/lib/MulticastListener.cpp, agent-ovs/lib/test/ServiceManager_test.cpp, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/FlowUtils.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/SwitchConnection.cpp, agent-ovs/ovs/test/AdvertManager_test.cpp, agent-ovs/ovs/test/ContractStatsManager_test.cpp, agent-ovs/ovs/test/InterfaceStatsManager_test.cpp, agent-ovs/ovs/test/PacketInHandler_test.cpp, agent-ovs/ovs/test/PortMapper_test.cpp, agent-ovs/ovs/test/SecGrpStatsManager_test.cpp, libopflex/engine/include/opflex/engine/Inspector.h, libopflex/modb/include/opflex/modb/internal/ObjectStore.h, libopflex/modb/include/opflex/modb/internal/Region.h, libopflex/modb/test/TestListener.h
=> Cleanup unneeded includes

agent-ovs/lib/ExtraConfigManager.cpp, agent-ovs/lib/FSPacketDropLogConfigSource.cpp, agent-ovs/lib/include/opflexagent/ExtraConfigListener.h, agent-ovs/lib/include/opflexagent/ExtraConfigManager.h, agent-ovs/lib/include/opflexagent/FSPacketDropLogConfigSource.h, agent-ovs/lib/include/opflexagent/PacketDropLogConfig.h, agent-ovs/lib/test/ExtraConfigManager_test.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/PacketLogHandler.cpp, agent-ovs/ovs/include/AccessFlowManager.h, agent-ovs/ovs/include/IntFlowManager.h, agent-ovs/ovs/include/OVSRenderer.h, agent-ovs/ovs/include/PacketDecoder.h, agent-ovs/ovs/include/PacketLogHandler.h, agent-ovs/ovs/test/PacketDecoder_test.cpp, genie/MODEL/OWNERSHIP/own.mdl, genie/MODEL/SPECIFIC/OBSERVER/config.mdl
Accept 5-tuple filters in droplog config file.
TODO: Add more tests and test on setup
=> Add user configurable pruning for drop-logs

agent-ovs/configure.ac, agent-ovs/debian/libopflex-agent.shlibs, genie/configs/genie.cfg, genie/pom.xml, genie/src/main/java/org/opendaylight/opflex/genie/content/format/agent/build/automake/cpp/FConfigureAC.java, libopflex/configure.ac
=> Bump versions for next release

agent-ovs/ovs/PacketLogHandler.cpp, agent-ovs/ovs/include/PacketDecoder.h, agent-ovs/ovs/include/PacketLogHandler.h, agent-ovs/ovs/test/PacketDecoder_test.cpp
Adding v6 MDNS packets from testing on openshift
Fix protocol number matching for known protocols
=> Add more default droplog pruning

agent-ovs/ovs/include/PacketLogHandler.h
Initializer was set to the first byte only.
=> Fix an issue in mac mask match

agent-ovs/ovs/PacketLogHandler.cpp, agent-ovs/ovs/include/PacketDecoder.h, agent-ovs/ovs/include/PacketLogHandler.h, agent-ovs/ovs/test/PacketDecoder_test.cpp
=> Backport droplog pruning

agent-ovs/cmd/test/Policies.cpp, agent-ovs/cmd/test/framework_stress.cpp, agent-ovs/cmd/test/mock_server.cpp, agent-ovs/server/StatsIO.cpp, agent-ovs/server/opflex_server.cpp, libopflex/cwrapper/test/cwrapper_test.cpp, libopflex/engine/GbpOpflexServer.cpp, libopflex/engine/include/opflex/engine/internal/GbpOpflexServerImpl.h, libopflex/engine/test/Processor_test.cpp, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/include/opflex/test/GbpOpflexServer.h
=> Changes to display modb objects in opflex-server via gbpinspect

agent-ovs/lib/ExtraConfigManager.cpp, agent-ovs/lib/FSPacketDropLogConfigSource.cpp, agent-ovs/lib/include/opflexagent/ExtraConfigManager.h, agent-ovs/lib/test/ExtraConfigManager_test.cpp, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/IntFlowManager.cpp
Separate delete call.
Add some more safeguards.
(cherry picked from commit 1f5032f2c73f61b4dac48e22061fe9b8473ed47c)
=> Fix tsan error in droplog

docs/building_and_running.md
=> Minor updates to build instructions

agent-ovs/lib/FSFaultSource.cpp, agent-ovs/lib/QosManager.cpp, agent-ovs/lib/include/opflexagent/QosManager.h, agent-ovs/lib/test/FaultManager_test.cpp, agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/QosRenderer.cpp, agent-ovs/ovs/test/OvsdbConnection_test.cpp, agent-ovs/ovs/test/QosRenderer_test.cpp, agent-ovs/server/GbpClient.cpp, agent-ovs/server/include/GbpClient.h, libopflex/configure.ac
Remove some unused includes/code
Use same min boost version for all components
GbpClient: Avoid joining thread multiple times
=> Increase UT coverage for QOS

agent-ovs/lib/FSFaultSource.cpp, agent-ovs/lib/FaultManager.cpp, agent-ovs/lib/include/opflexagent/FaultManager.h
fixed the indentations
removed unused headers 
other clean ups
=> cleaned up Faultmanager and FSfaultsource

agent-ovs/lib/ExtraConfigManager.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp
Remove a couple of unused includes
=> Increase UT coverage for droplog feature

.travis.yml, .travis/install-dependencies.sh
=> Move travis builds to focal

agent-ovs/lib/test/FaultManager_test.cpp
Signed-off-by: bashokba <bashokba@cisco.com>
=> Fixed ep-fault UT failures.

libopflex/cwrapper/test/cwrapper_test.cpp, libopflex/engine/test/Processor_test.cpp
=> Address ASAN issues in some recently added tests

libopflex/comms/transport/PlainText.cpp
=> Increase default buffer size used for OVSDB communication

libopflex/comms/transport/PlainText.cpp
=> Increase default buffer size used for OVSDB communication (#345)

agent-ovs/ovs/QosRenderer.cpp
=> Add missing call to renderer stop in superclass

agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/include/opflexagent/PolicyManager.h, agent-ovs/lib/test/PolicyManager_test.cpp, genie/MODEL/EXTENSIONS/GBP/extensions.mdl
=> Genie model for egress DNS policy

agent-ovs/debian/control
=> Add curl as dep for debian builds for UTs

agent-ovs/lib/Agent.cpp
=> Address TSAN issue reported on Ubuntu 20.10

agent-ovs/lib/SysStatsManager.cpp
=> Init var in constructor to address coverity complaint

agent-ovs/Makefile.am, agent-ovs/configure.ac
Code won't compile without prometheus-cpp 0.12.1+
=> Remove prometheus conditionals from build scripts

agent-ovs/lib/test/NotifServer_test.cpp, agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/PacketLogHandler.cpp, agent-ovs/ovs/include/DnsManager.h
=> Fix some TSAN and coverity issues

libopflex/engine/OpflexServerHandler.cpp
=> Properly detect unavailable policy on the opflex-server

agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/include/DnsManager.h, agent-ovs/ovs/test/DnsManager_test.cpp
Process the canonical name record
Do loop check and reject records if loopy
Handle recursive resolution with expiry
Refactored code to move DnsRR out of DnsParsingContext to handle union. 
TODO:
More test-cases to cover loopcheck and expiry
=> Handle DNS recursive resolution

agent-ovs/lib/EndpointManager.cpp
=> Fix build error due to missing include

agent-ovs/lib/EndpointManager.cpp
=> Fix build error due to missing include.

agent-ovs/lib/QosManager.cpp, agent-ovs/lib/include/opflexagent/QosManager.h, agent-ovs/lib/test/QosManager_test.cpp
Computed values were not being used outside of UTs
=> Remove some qos related processing

.travis/travis-build.sh, agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/test/DnsManager_test.cpp
Add expiry and restore cases for the included record types.
=> More DNS tests

agent-ovs/ovs/NetFlowRenderer.cpp
Set default values for enable_input_sampling & enable_output_sampling which is true.
=> Set enable_input_sampling & enable_output_sampling to true

agent-ovs/Makefile.am, agent-ovs/lib/include/opflexagent/LearningBridgeManager.h, agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/test/PacketInHandler_test.cpp, libopflex/Makefile.am, libopflex/comms/CommunicationPeer.cpp, libopflex/include/opflex/yajr/async_doc_parser.hpp
supports
- g++ 11.3.1
- boost 1.75.0-8
Also fixes a tsan issue for instance_count_ that only effects logging
=> Fixes for centos9 build

.github/workflows/codeql-analysis.yml
Running on each push + PRs is enough
=> Disable periodic code runs

.github/workflows/codeql-analysis.yml, .github/workflows/codeql-filters.yml
Update code checkout steps to match latest pattern
=> Add filter to exclude some noisy CodeQL checks

.github/codeql-filters.yml, .github/workflows/codeql-analysis.yml, agent-ovs/lib/Network.cpp, agent-ovs/lib/include/opflexagent/Network.h
Move == operator definition to struct instead
Also suppress another noisy CodeQL rule
=> Fix agent compilation issue with Ubuntu 23.04

agent-ovs/lib/PolicyManager.cpp
These result in updateEPGDomains always returning true that significantly increases the amount of time updateDomain takes when a large number of subnets are present.
With bosch config the order of improvement is from 40 mins down to 4 mins.
Additionally only copy objects that changed resulting in a 25% improvement.
=> Fix broken shared_ptr compares

agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/include/OVSRenderer.h
Run NetFlowRenderer with with intBridgeName switch and accessBridgeName switch.
=> Run multiple switches on NetFlowRenderer

agent-ovs/lib/FSPacketDropLogConfigSource.cpp, agent-ovs/lib/LearningBridgeManager.cpp, agent-ovs/lib/PolicyManager.cpp, agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/OvsdbTransactMessage.cpp, agent-ovs/ovs/PacketInHandler.cpp, libopflex/comms/test/comms_test.cpp, libopflex/engine/InspectorClientImpl.cpp, libopflex/engine/OpflexPool.cpp, libopflex/include/opflex/yajr/async_doc_parser.hpp
New coverity version complains about copies where move is possible
Also some new complaints about pass-by-ref possibilities
=> Address coverity complaints with latest run

agent-ovs/ovs/AccessFlowManager.cpp
It was added long back for some openstack customer and only handled V4. This was causing a mess up
of dual-stack service flows. Fixed that.
=> Make svc bypass code dual-stack aware

agent-ovs/cmd/opflex_agent.cpp
write to reset.conf in one of the config dir, for example /usr/local/var/lib/opflex-agent-ovs/reboot-conf.d/reset.conf
This would produce the following log messages
[2023-Nov-17 13:56:19.859957] [info] [cmd/opflex_agent.cpp:154:updated] Triggering peer reset because of change to "/usr/local/var/lib/opflex-agent-ovs/reboot-conf.d/reset.conf" [2023-Nov-17 13:56:19.860098] [info] [cmd/opflex_agent.cpp:121:run] Disconnect from existing peers and fallback to configured list because of configuration update
The effect will be the same as what happens to the connection when PlatformConfig is deleted.
=> Add support to reset opflex peers via config files.

.travis.yml
(cherry picked from commit 0143515edeee5e33bfd49d2f8fdebfbde3eaf1d6)
=> Adding fix for travis docker buildx issue

.travis.yml, .travis/install-dependencies.sh
(cherry picked from commit 914b0e742de650c158e7fcc8dda17429138e78f1)
=> Test with OpenSSL 3+ (#477)

agent-ovs/lib/include/opflexagent/PrometheusManager.h, agent-ovs/ovs/include/SpanRenderer.h, agent-ovs/ovs/include/SwitchConnection.h, libopflex/engine/OpflexPEHandler.cpp, libopflex/engine/OpflexPool.cpp, libopflex/engine/include/opflex/engine/internal/OpflexHandler.h, libopflex/include/opflex/rpc/JsonRpcConnection.h
+ some minor doc fixes
(cherry picked from commit b262d5f11fc13f81abf5bff8809dd10389409ea6)
=> Fix compilation errors w/ Ubuntu 23.10

docker/travis/Dockerfile-opflex
(cherry picked from commit 57b72c8c6ac1d524e8fb51be1c5de538929540e5)
=> Fix quay security scanner issues.

docker/travis/Dockerfile-opflex
(cherry picked from commit e175ee7653f83a9fc10d73352521baaa97d200ba)
=> Fix broken build

.github/workflows/codeql-analysis.yml
Also move to Ubuntu 22.04 builds on github to match travis
=> Bump CodeQL action versions

agent-ovs/lib/FSWatcher.cpp
=> Fix crash in inotify read.

agent-ovs/cmd/mcast_daemon.cpp, agent-ovs/cmd/test/policy_repo_stress.cpp, agent-ovs/lib/Agent.cpp, agent-ovs/lib/AgentPrometheusManager.cpp, agent-ovs/lib/FSWatcher.cpp, agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/QosManager.cpp, agent-ovs/lib/SysStatsManager.cpp, agent-ovs/lib/test/EndpointManager_test.cpp, agent-ovs/lib/test/FaultManager_test.cpp, agent-ovs/lib/test/PolicyManagerIvLeaf_test.cpp, agent-ovs/lib/test/ServiceManager_test.cpp, agent-ovs/lib/test/SysStatsManager_test.cpp, agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/EndpointTenantMapper.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp, agent-ovs/ovs/test/ServiceStatsManager_test.cpp, agent-ovs/ovs/test/SpanRenderer_test.cpp, agent-ovs/ovs/test/include/PolicyStatsManagerFixture.h, agent-ovs/server/test/AgentStats_test.cpp, libopflex/comms/rpc/JsonRpcConnection.cpp, libopflex/engine/MOSerializer.cpp, libopflex/engine/OpflexPool.cpp, libopflex/engine/Processor.cpp
https://scan.coverity.com/projects/agent-ovs - latest reports
=> coverity statis analysis fixes

genie/pom.xml
Also bump min supported JDK version to 11
=> Bump maven plugins used by genie

agent-ovs/configure.ac, agent-ovs/debian/libopflex-agent.shlibs, genie/configs/genie.cfg, genie/pom.xml, libopflex/configure.ac
This reverts commit a12b020f4abf380cc728220ff2687c3ef9a533dc.
=> Revert "Bump version for LMR release"

.github/codeql-filters.yml, genie/src/main/java/org/opendaylight/opflex/genie/content/format/agent/structure/cpp/FClassDef.java
Exclude another CodeQL check
(cherry picked from commit dcbdf31da73d271dcce4e2d68994844aef0e073a)
=> Change code generation to inherit from concrete superclasses (#501)

agent-ovs/lib/EndpointManager.cpp, agent-ovs/ovs/OvsdbConnection.cpp, genie/src/main/java/org/opendaylight/opflex/genie/content/format/agent/structure/cpp/FClassDef.java, libopflex/engine/MOSerializer.cpp
Address some linter complaints
Avoid generating some unused code
(cherry picked from commit e1101eb3e6d5fc44172e4d477ca6ce0943fd6450)
=> Fix logic issue in last change (#507)

.github/workflows/codeql-analysis.yml
(cherry picked from commit 9611922619cae51e594c8441ed9703cbb236725a)
=> Bump GHA version to quell warning (#512)

agent-ovs/cmd/mcast_daemon.cpp, agent-ovs/cmd/test/policy_repo_stress.cpp, agent-ovs/lib/Agent.cpp, agent-ovs/lib/AgentPrometheusManager.cpp, agent-ovs/lib/FSWatcher.cpp, agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/QosManager.cpp, agent-ovs/lib/SysStatsManager.cpp, agent-ovs/lib/test/EndpointManager_test.cpp, agent-ovs/lib/test/FaultManager_test.cpp, agent-ovs/lib/test/PolicyManagerIvLeaf_test.cpp, agent-ovs/lib/test/ServiceManager_test.cpp, agent-ovs/lib/test/SysStatsManager_test.cpp, agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/EndpointTenantMapper.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp, agent-ovs/ovs/test/ServiceStatsManager_test.cpp, agent-ovs/ovs/test/SpanRenderer_test.cpp, agent-ovs/ovs/test/include/PolicyStatsManagerFixture.h, agent-ovs/server/test/AgentStats_test.cpp, libopflex/comms/rpc/JsonRpcConnection.cpp, libopflex/engine/MOSerializer.cpp, libopflex/engine/OpflexPool.cpp, libopflex/engine/Processor.cpp
Co-authored-by: bhavana babu <bhavana.babu32@gmail.com>
(cherry picked from commit 0354ac9a1f3cc27334f8fd7286b5e15549bd1aa8)
=> addressing defects from coverity statis analysis (#511)

docker/travis/Dockerfile-opflex-build-base
(cherry picked from commit c2616782ccfa4f264a9ae62f26e4205bfdd6036a)
=> Need to manually copy re2.pc and libasl* to build w/ gcp 1.52.2 (#513)

agent-ovs/lib/include/opflexagent/EndpointListener.h, agent-ovs/lib/include/opflexagent/ExtraConfigManager.h, agent-ovs/lib/include/opflexagent/FaultManager.h, agent-ovs/lib/include/opflexagent/NetFlowManager.h, agent-ovs/lib/include/opflexagent/QosManager.h, agent-ovs/lib/include/opflexagent/ServiceManager.h, agent-ovs/lib/include/opflexagent/SnatManager.h, agent-ovs/lib/include/opflexagent/SpanManager.h, agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/include/OvsdbMessage.h, agent-ovs/ovs/include/OvsdbMonitorMessage.h, agent-ovs/ovs/include/OvsdbState.h, agent-ovs/ovs/include/OvsdbTransactMessage.h
(cherry picked from commit 8518f9c0a29cc8c6fdf5b12b3f2b31748e2777cd)
=> Fix compilation issues w/ gcc 13

libopflex/rpm/libopflex.spec.in
(cherry picked from commit 81e16aaa31e971ccaeb3484eeba969a880ee1d64)
=> Missed updating RPM spec to require OpenSSL 1.1+ (#528)

agent-ovs/lib/Agent.cpp, agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/QosManager.cpp, agent-ovs/ovs/Packets.cpp, agent-ovs/ovs/SpanRenderer.cpp, libopflex/engine/MOSerializer.cpp
(cherry picked from commit 04daadc625c22f1bbfb3af84003fcde0d570e64c)
=> Address a few more low priority coverity complaints

agent-ovs/ovs/SecGrpStatsManager.cpp, agent-ovs/ovs/include/SecGrpStatsManager.h
agent declared protected in base class
=> Address code review comments

docker/travis/Dockerfile-opflex, docker/travis/Dockerfile-opflex-build-base, docker/travis/Dockerfile-opflexserver
(cherry picked from commit fe67e584afbfa3246341c36e935f299f41cfd984)
=> Updating ubi9-minimal tag to latest to resolve CVEs

docker/rpms/Dockerfile-opflexrpm-build, docker/rpms/Dockerfile-opflexrpm-build-base, docker/rpms/README.txt, docker/rpms/build_opflex_baserpm.sh, docker/rpms/build_opflexrpm.sh
See rpms/README.txt
Address Toms comments and fixed few more issues
- copy all rpms including from base image into final
- change build_opflexrpm.sh to pass branch and rpm version to build
- update README.txt
(cherry picked from commit e0e4184fa47a79e84be7257e5814c32f27ed770c)
=> Add support for ubi8 rpmbuild

docker/travis/Dockerfile-opflex
(cherry picked from commit 14b2c0d3f9531b0edfc2ccfcc6735b1da9d79192)
=> Adding fix to address high-cves for opflex build

docker/travis/build-opflex-travis.sh
(cherry picked from commit 61deb90c9bb5517ee23d8c4102436b65f59f7d95)
=> Adding changes to build-travis.sh for building base then opflex images

docker/travis/Dockerfile-opflex, docker/travis/Dockerfile-opflex-build-base, docker/travis/Dockerfile-opflexserver
This is temporary to see if we get a clean run. We will revisit this after that.
=> Revert libssl fixes

docker/travis/build-opflex-travis.sh
to only build opflex-build-base image
if a tag comtaining "opflex-build-base" is pushed
=> update opflex build

docker/travis/Dockerfile-opflex, docker/travis/Dockerfile-opflex-build-base, docker/travis/Dockerfile-opflexserver
- remove compat-openssl11-1:1.1.1k-4.el9_0
- add strace
=> Update from 9.3 to latest

.github/workflows/push-git-tag.yaml
-  if a *-opflex-build-base git tag is pushed wait for its travis job to complete successfully
and push a branch tag after that.
=> Add github workflow

agent-ovs/lib/PolicyManager.cpp
This fixes a link issues with templates.
=> Fix template instantiation

.github/workflows/push-git-tag.yaml
added missing semicolon and corrected comment syntax
=> Updated github workflow syntax

docker/travis/Dockerfile-opflex
to avoid conflicting pkg versions
=> Excludes openssl from updates

agent-ovs/ovs/IntFlowManager.cpp
creates inconsistent behavior based on ordering of Mos otherwise
=> Add non nat flow until natEpgVnid is resolved.
