noironetworks/opflex

agent-ovs/lib/include/opflexagent/test/ModbFixture.h, agent-ovs/ovs/FlowUtils.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp
This reverts commit 38bc9a134322cd0c5ce1c63338b17ed91442caaa.
This patch was reverted in order to support AIM, which currently
doesn't explicitly configure the ICMP type/code values as
"unspecified". If not specified, their default values of 0 are
used, which renders the classifiers into flow-mods that cause
the ICMP packets to be (erroneously) dropped.
=> Revert "Add flow-rules to support ICMP type/code in L24Classifier"

agent-ovs/lib/LearningBridgeManager.cpp
This code gets triggered on handlePortStatusUpdate and would result in the
opflex agent getting stuck in an infinite loop because the iterator is
not being incremented in the while loop.
---------------------------------------------------------------------------
Simple way to repro the issue is to add or del the patch ports on br-fabric
example:
ovs-vsctl del-port br-fabric qpi2b4b79dd-6e
ovs-vsctl add-port br-fabric qpi2b4b79dd-6e -- set interface qpi2b4b79dd-6e type=patch options:peer=qpf2b4b79dd-6e
Or
ovs-vsctl del-port br-fabric patch-fabric-ex
ovs-vsctl add-port br-fabric patch-fabric-ex -- set interface patch-fabric-ex type=patch options:peer=patch-ex-fabric
---------------------------------------------------------------------------
Verified we come out of the loop with the fix. …
=> Fix infinite loop in getVlanRangesByIface

agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/test/AccessFlowManager_test.cpp
We currently create 2 dhcp rules with same priority 200 for untagged and
tagged traffic on the same port. The result is that we end up hitting
the first rule even for the vlan traffic preventing the sub-interface
from acquiring the dhcp ip address.
Without the fix the rules look like this.
cookie=0x0, duration=3.957s, table=0, n_packets=0, n_bytes=0, priority=200,udp,in_port=1,tp_src=68,tp_dst=67 actions=load:0x6->NXM_NX_REG7[],goto_table:3
cookie=0x0, duration=4.299s, table=0, n_packets=0, n_bytes=0, priority=200,udp,in_port=1,dl_vlan=4094,tp_src=68,tp_dst=67 actions=load:0x6->NXM_NX_REG7[],write_metadata:0x1/0xff,goto_table:3
With the fix the second rule would look like this.
cookie=0x0, duration=4.299s, table=0, n_packets=0, n_bytes=0, …
=> Rule priority incorrect for opflex trunk ports.

agent-ovs/rpm/opflex-agent.spec.in
Commit 9e345a4644e1a4cc589463772e9700cf970db858 introduced an
openvswitch-specific directory for caching state. Since there
currently is only one dataplane supported (OVS), this patch
goes back to using a single directory, which simplifies the
installers. Multiple state directories should be introduced
once multiple dataplanes are supported by the agent.
=> Remove separate state directory for OVS

agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp
This happen due to the following rule.
cookie=0x0, duration=6892.708s, table=3, n_packets=0, n_bytes=0, priority=51,arp,reg4=0x1,reg6=0x1,dl_dst=ff:ff:ff:ff:ff:ff,arp_tpa=192.168.0.2,arp_op=1 actions=move:NXM_OF_ETH_SRC[]->NXM_OF_ETH_DST[],load:0xfa163e5239f4->NXM_OF_ETH_SRC[],load:0x2->NXM_OF_ARP_OP[],move:NXM_NX_ARP_SHA[]->NXM_NX_ARP_THA[],load:0xfa163e5239f4->NXM_NX_ARP_SHA[],move:NXM_OF_ARP_SPA[]->NXM_OF_ARP_TPA[],load:0xc0a80002->NXM_OF_ARP_SPA[],IN_PORT
The goal is to not respond to similar arp request on the fabric uplink.
We solve this by adding a higher priority rule that looks like this, note the match on in_port=<tunnel_port> and action=drop.
cookie=0x0, duration=6892.708s, table=3, n_packets=0, n_bytes=0, priority=52,arp,reg4=0x1,reg6=0x1,in_port=3,dl_dst=ff:ff:ff:ff:ff:ff,arp_ …
=> Agent replying to arp with dhcp ip on native vlan.

agent-ovs/ovs/TableState.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp
Flags updated for existing flows were not getting reflected.
Fix this by checking for flags explicitly if rest of the flow
matches and do a flow mod with flags in this case.
=> Flag reconciliation

agent-ovs/ovs/SwitchConnection.cpp
Original behavior before timeout param was added to
vconn_open_block was to retry OF connection indefinitely
Setting the timeout behavior to 0 meant no retries at all.
Changing the setting to -1 restores the original behavior
=> Restore OVS connection behavior from before OVS 2.12 upgrade

.travis/asan-build.sh, .travis/travis-build.sh, .travis/tsan-build.sh, agent-ovs/Makefile.am, agent-ovs/configure.ac, libopflex/Makefile.am, libopflex/comms/Makefile.am, libopflex/configure.ac, libopflex/cwrapper/Makefile.am, libopflex/cwrapper/test/Makefile.am, libopflex/engine/Makefile.am, libopflex/engine/test/Makefile.am, libopflex/logging/Makefile.am, libopflex/modb/Makefile.am, libopflex/modb/test/Makefile.am, libopflex/ofcore/Makefile.am, libopflex/ofcore/test/Makefile.am, libopflex/util/Makefile.am
No issues currently seen with either when running make check locally
Also redirect agent configure output to /dev/null in travis builds
=> Add configure option to enable UBSAN

agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/TableState.cpp, agent-ovs/ovs/include/TableState.h, lgtm.yml, libopflex/comms/transport/ZeroCopyOpenSSL.cpp
Enable more checks.
Virtual method issues reported are fine because they happen in destructors and the behavior is intended.
Assignment operator requirements are about readability.
=> More LGTM fixes

agent-ovs/cmd/test/policy_repo_stress.cpp, agent-ovs/lib/EndpointManager.cpp, agent-ovs/lib/PrometheusManager.cpp, agent-ovs/lib/SimStats.cpp, agent-ovs/lib/include/opflexagent/EndpointManager.h, agent-ovs/lib/include/opflexagent/PrometheusManager.h, agent-ovs/lib/test/EndpointManager_test.cpp, agent-ovs/ovs/InterfaceStatsManager.cpp, agent-ovs/ovs/include/InterfaceStatsManager.h
- stopped relying on observer mo to update EpCounter metrics
- create/del checks along with stats updates
- label hash change checks during mod
- removed unused function
- since forward declaration of nested class/struct/type isnt allowed in c++, had to un-nest EpCounters
=> Adding prometheus UT for EpCounter and cleanup

agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/test/include/PolicyStatsManagerFixture.h
- lgtm: Comparison result is always the same:
We seem to be checking if l4_size is < sizeof(icmp6_hdr) above already. Hence removing "if (l4_size < sizeof(*router_sol))" which is reduntant.
struct nd_router_solicit {  /* router solicitation */
struct icmp6_hdr  nd_rs_hdr;
/* could be followed by options */
};
- coverty: fix null ptr dereference and unreachable code
=> address few more lgtm and coverty issues

agent-ovs/ovs/AdvertManager.cpp
Any of the timer cancels can fail, but the timer handlers check the return value
and return doing nothing, so this should be safe to do.
=> Fix a coverity issue.

agent-ovs/cmd/test/opflex_server.cpp, libopflex/engine/OpflexPool.cpp
Root cause:
During leaf replacement of VPC member, the tep ip of replaced leaf changes. Due to this we remove the stale opflex peer connection and add new tep ip of replaced leaf. During this process we seem to be hitting crash due to hoisting issue in BOOST_FOREACH.
More details on this here: https://www.boost.org/doc/libs/1_73_0/doc/html/foreach/pitfalls.html
Tests performed:
./opflex_server --policy=/home/noiro/work/opflex/agent-ovs/policy.json --peer "127.0.0.1:8010" <-- this is agent's configured peer that listens on 8009
./opflex_server --policy=/home/noiro/work/opflex/agent-ovs/policy.json --peer "127.0.0.1:8011" --peer "127.0.0.1:8012" --server_port 8010
./opflex_server --policy=/home/noiro/work/opflex/agent-ovs/policy.json --peer "127.0.0.1:8012" --peer "127.0.0.1:8013" …
=> Fix for agent crash reported in CSCvu46192/SR689109894

libopflex/engine/OpflexPool.cpp, libopflex/engine/include/opflex/engine/internal/OpflexPool.h, libopflex/engine/test/OpflexPool_test.cpp
=> Remove never used OpflexPool::getMasterForRole

agent-ovs/ovs/test/IntFlowManager_test.cpp
As part of intflowmanager.configUpdated(), first platform config's mcast ip will get added to mcast path; then epg2 egDomUpdated will result in the next mcast ip to get added. Waiting for both of them to get added for the test to be reliable.
=> fix for a flaky test

.travis.yml, .travis/travis-build.sh, agent-ovs/Makefile.am, agent-ovs/configure.ac, libopflex/Makefile.am, libopflex/comms/Makefile.am, libopflex/configure.ac, libopflex/cwrapper/Makefile.am, libopflex/cwrapper/test/Makefile.am, libopflex/engine/Makefile.am, libopflex/engine/test/Makefile.am, libopflex/logging/Makefile.am, libopflex/modb/Makefile.am, libopflex/modb/test/Makefile.am, libopflex/ofcore/Makefile.am, libopflex/ofcore/test/Makefile.am, libopflex/util/Makefile.am
- Config options added for libopflex and agent-ovs. By default its disabled.
- Gprof uses instrumentation and sampling to generate profiling data. Due to sampling it is fast, but might be inaccurate due to rate of sampling. But call counts and approximate call graphs will help pinpoint most common bottlenecks. More details here: https://ftp.gnu.org/old-gnu/Manuals/gprof-2.9.1/html_mono/gprof.html.
- To avoid overhead, gprof output is enabled only in vanilla agent-ovs build in travis (which will cover libopflex as well). And top 20 methods and top 100 lines of call stack are dumped for now.
- Will be useful to run it on standalone opflex-agent to analyze the bottlenecks.
Note: I tried perf as well. But the output was showing more info on kernel and system call profiling. Regarding …
=> Support for gprof profiler for libopflex and agent-ovs

agent-ovs/ovs/FlowUtils.cpp, agent-ovs/ovs/test/AccessFlowManager_test.cpp
- The related flows added against l24 classifer rules will not match
since they have a different protocol (like icmp)
- Fix this by matching only on the l3 type
- The flags need to be a complete set of what ct returns, unspecified
flags should be wildcarded but thats not how ovs is matching it.
- Fix the flags to include rel+rpl
=> Fix related flows like icmp port unreachable

agent-ovs/lib/PolicyManager.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp
- mcast: Found that some of the events happen just after the test fails. Increasing retry count.
- routingDomainUnenforcedMode: test fails if policy manager updates group_map after intflowmanager.egDomUpd() gets called. Registering listener updates from policy manager to fix ordering issues. EPG updates will be trigged by policy manager updates now.
- remoteInventoryMode: same fix as routingDomainUnenforced
=> Fix for flaky tests in agent-ovs

agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/test/OvsdbConnection_test.cpp
Avoid unnecessarily writing OVSDB payload into a buffer
Remove mocked calls to handleUpdate with incorrect payload
=> Avoid unnecessarily writing OVSDB payload into a buffer

libopflex/engine/include/opflex/engine/internal/OpflexPool.h
355 WARNING: ThreadSanitizer: data race (pid=8183)
356   Write of size 8 at 0x7b7800000548 by thread T11 (mutexes: write M1342):
357     #0 opflex::engine::internal::OpflexPool::setTunnelMac(opflex::modb::MAC const&) include/opflex/engine/internal/OpflexPool.h:338 (libopflex.so.0+0x115151)
358     #1 opflex::engine::Processor::setTunnelMac(opflex::modb::MAC const&) /home/noiro/work/opflex/libopflex/engine/Processor.cpp:584 (libopflex.so.0+0x115151)
359     #2 opflex::ofcore::OFFramework::setTunnelMac(opflex::modb::MAC const&) /home/noiro/work/opflex/libopflex/ofcore/OFFramework.cpp:103 (libopflex.so.0+0x18dcca)
360     #3 opflexagent::Agent::setUplinkMac(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) lib/Agent.cpp:795 …
=> Protecting pool's tunnel mac update with mutex

agent-ovs/Makefile.am, agent-ovs/configure.ac, agent-ovs/ovs/include/ovs-shim.h, agent-ovs/ovs/ovs-shim.c, libopflex/Makefile.am, libopflex/comms/Makefile.am, libopflex/configure.ac, libopflex/cwrapper/Makefile.am, libopflex/cwrapper/test/Makefile.am, libopflex/engine/Makefile.am, libopflex/engine/OpflexPool.cpp, libopflex/engine/include/opflex/engine/internal/OpflexListener.h, libopflex/engine/include/opflex/engine/internal/OpflexPool.h, libopflex/engine/test/Makefile.am, libopflex/logging/Makefile.am, libopflex/modb/Makefile.am, libopflex/modb/test/Makefile.am, libopflex/ofcore/Makefile.am, libopflex/ofcore/test/Makefile.am, libopflex/util/Makefile.am
Require c++11 support to build libopflex
Require c++14 support to build agent-ovs
Remove some of the #ifdefs used to support older versions
Remove some unused code in ovs-shim
=> Require c++11 support to build libopflex, c++14 for agent-ovs

agent-ovs/Makefile.am, agent-ovs/configure.ac
Temporarily revert move to C++14 for opflex_agent
Ran into some RPM build issues that need to be
resolved before moving forward with this change
=> Temporarily revert move to C++14 for opflex_agent

.travis/asan-build.sh, .travis/travis-build.sh, .travis/tsan-build.sh, .travis/ubsan-build.sh
- Trap ERR to pinpoint failed line in the script
- Exit travis in case of build errors using "set -e".
- Cache return code of agent's make check and exit with that.
=> Fix to catch and exit travis with error code

libopflex/engine/OpflexClientConnection.cpp, libopflex/engine/OpflexPool.cpp, libopflex/engine/include/opflex/engine/Processor.h, libopflex/engine/include/opflex/engine/internal/OpflexPool.h
Whenever a connection is destroyed, we need to clear the pending resolutions for that connection. Without this, unresolved counts and pending resolutions can get out of sync.
=> Fix for large values of policy unresolved counts

agent-ovs/Makefile.am, agent-ovs/cmd/test/ServerPrometheusManager.cpp, agent-ovs/cmd/test/opflex_server.cpp, agent-ovs/lib/Agent.cpp, agent-ovs/lib/AgentPrometheusManager.cpp, agent-ovs/lib/EndpointManager.cpp, agent-ovs/lib/FSEndpointSource.cpp, agent-ovs/lib/ModelEndpointSource.cpp, agent-ovs/lib/ServiceManager.cpp, agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/lib/include/opflexagent/EndpointManager.h, agent-ovs/lib/include/opflexagent/PrometheusManager.h, agent-ovs/lib/include/opflexagent/ServiceManager.h, agent-ovs/ovs/TableDropStatsManager.cpp, agent-ovs/ovs/include/IntFlowManager.h, agent-ovs/ovs/include/PolicyStatsManager.h
- refactored existing PrometheusManager implementation so that agent and server implementations are kept separate
- Commonalities are kept in "PrometheusManager"
- exposing on port 9632 from opflex-server
- added config knobs to disable prometheus and expose only on localhost
- tested manually
TODO:
- this is first cut. metrics to be added
- uts to be added
=> Integrating PrometheusManager with opflex-server

agent-ovs/ovs/IntFlowManager.cpp
- Not having source mac is causing the leaf to get a packet
with its own mac as src-mac that is causing it to move the
EP
- this sends a well known mac of the snat-ifc as src mac
=> Add src mac for snat bounce

agent-ovs/cmd/test/GbpClient.cpp, agent-ovs/cmd/test/ServerPrometheusManager.cpp, agent-ovs/cmd/test/include/GbpClient.h, agent-ovs/cmd/test/opflex_server.cpp
- Cleaning up prometheus before execv
- addressing typo and indentation
- addressing couple of data races when policy path dir changes
Issue 1: protecting client_ access
WARNING: ThreadSanitizer: data race (pid=13435)
Read of size 8 at 0x7ffd9def3db8 by main thread:
#0 opflexagent::GbpClient::Stop() cmd/test/GbpClient.cpp:214 (opflex_server+0xe4a9e)
#1 main cmd/test/opflex_server.cpp:290 (opflex_server+0x945e7)
Previous write of size 8 at 0x7ffd9def3db8 by thread T1:
#0 opflexagent::GbpClient::Start(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) cmd/test/GbpClient.cpp:206 (opflex_server+0xe4e0d)
Issue 2: atomic bool
WARNING: ThreadSanitizer: data race (pid=1993)
Read of size 1 at 0x7ffd965bd3e0 by thread T1:
#0 …
=> fix for tsan issues in opflex-server and clean prometheus before execv

agent-ovs/ovs/test/include/MockRpcConnection.h, libopflex/comms/CommunicationPeer.cpp, libopflex/comms/ListeningPeer.cpp, libopflex/comms/passive_listener.cpp, libopflex/comms/peer.cpp, libopflex/comms/rpc.cpp, libopflex/comms/rpc/JsonRpcConnection.cpp, libopflex/comms/test/comms_test.cpp, libopflex/comms/transport/PlainText.cpp, libopflex/cwrapper/test/cwrapper_test.cpp, libopflex/engine/InspectorClientConn.cpp, libopflex/engine/InspectorClientImpl.cpp, libopflex/engine/OpflexListener.cpp, libopflex/engine/Processor.cpp, libopflex/engine/include/opflex/engine/Inspector.h, libopflex/engine/test/Processor_test.cpp, libopflex/include/opflex/util/ThreadManager.h, libopflex/include/opflex/yajr/internal/comms.hpp, libopflex/ofcore/OFFramework.cpp, libopflex/ofcore/test/Inspector_test.cpp
Addressing coverity and clang-tidy issues
Init members before use
Remove unneeded #include statements
Prefer std::unique_ptr over boost::scoped_ptr
=> Addressing coverity and clang-tidy issues

agent-ovs/cmd/test/policy_repo_stress.cpp, agent-ovs/lib/test/LearningBridgeManager_test.cpp, agent-ovs/ovs/Packets.cpp, agent-ovs/ovs/test/ContractStatsManager_test.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp, agent-ovs/ovs/test/SecGrpStatsManager_test.cpp, agent-ovs/ovs/test/ServiceStatsManager_test.cpp, agent-ovs/ovs/test/TableDropStatsManager_test.cpp, agent-ovs/ovs/test/include/PolicyStatsManagerFixture.h, libopflex/comms/test/comms_test.cpp, libopflex/engine/OpflexClientConnection.cpp
=> clang-tidy: Prefer std::to_string over boost::lexical_cast

agent-ovs/cmd/test/opflex_server.cpp, agent-ovs/lib/Agent.cpp, agent-ovs/lib/include/opflexagent/Agent.h
- create framework and default inspector sock if not specified
- create DmtreeRoot
- Add the same set of universes during agent and server init under root
Tested in mock environment:
noiro@gautvenk-noiro-vm:~/work/opflex/agent-ovs$ sudo gbp_inspect --socket=/usr/local/var/run/opflex-server-inspect.sock -prq DmtreeRoot
____ DmtreeRoot,/
____ RelatorUniverse,/RelatorUniverse/
____ GbpeVMUniverse,/GbpeVMUniverse/
____ SpanUniverse,/SpanUniverse/
____ EpdrL2Discovered,/EpdrL2Discovered/
____ EpdrL3Discovered,/EpdrL3Discovered/
____ EpdrExternalDiscovered,/EpdrExternalDiscovered/
____ EpdrLocalRouteDiscovered,/EpdrLocalRouteDiscovered/
____ InvUniverse,/InvUniverse/
____ EprL2Universe,/EprL2Universe/
____ EprL3Universe,/EprL3Universe/
____ EprPeerRouteUniverse,/EprPeerRouteUniverse/
____ …
=> Add support for gbp_inspect to opflex server

agent-ovs/ovs/OvsdbConnection.cpp, genie/src/main/java/org/opendaylight/opflex/genie/content/format/agent/structure/cpp/FClassDef.java, genie/src/main/java/org/opendaylight/opflex/genie/content/format/proxy/structure/cpp/FClassDef.java
End result has always been correct but it results in unneeded processing
Also explicitly cleanup OVSDB resources
=> Stop using class IDs in relation URIs as they may change when upgrading

agent-ovs/lib/SpanManager.cpp, agent-ovs/lib/include/opflexagent/SpanManager.h, agent-ovs/lib/include/opflexagent/SpanSessionState.h, agent-ovs/lib/test/SimStats_test.cpp, agent-ovs/lib/test/SpanManager_test.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/include/SpanRenderer.h, agent-ovs/ovs/test/SpanRenderer_test.cpp
Allow output ports to be shared between sessions.
TODO: Need to cleanup output port after last mirror using it is removed
=> Remove support for EPG as src for ERSPAN session.

agent-ovs/Makefile.am
- gbp.grpc.pb.h moved inside agent-ovs/server. Updated Makefile include dirs to reflect the same.
- I had a local file which appears to have helped with the build earlier.
=> Fixing gbp_client_stress build

agent-ovs/server/opflex_server.cpp
Details of the warning:
if (execv(argv[0], argv)) { <-- The value of first argument may come from argv and is being passed to execv
https://lgtm.com/rules/2163130737/
Checking the executable string to end with opflex_server to avoid the warning.
=> Fixing lgtm warning in opflex server

agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp, libopflex/engine/Processor.cpp, libopflex/engine/include/opflex/engine/Processor.h
- when an RD is associated with two external domains,
one with SNAT and one without for same subnet the
behavior is undefined.
- This fix gives SNAT higher precedence.
- Added verbose names to Processer state machine.
=> Give SNAT higher precedence to routed

libopflex/engine/GbpOpflexServer.cpp, libopflex/engine/include/opflex/engine/internal/GbpOpflexServerImpl.h
==================
WARNING: ThreadSanitizer: data race (pid=19679)
Read of size 1 at 0x7b1000034990 by main thread:
#0 boost::asio::detail::deadline_timer_service<boost::asio::time_traits<boost::posix_time::ptime> >::cancel(boost::asio::detail::deadline_timer_service<boost::asio::time_traits<boost::posix_time::ptime> >
::implementation_type&, boost::system::error_code&) /usr/include/boost/asio/detail/deadline_timer_service.hpp:100 (libopflex.so.0+0x1630e3)
#1 boost::asio::deadline_timer_service<boost::posix_time::ptime, boost::asio::time_traits<boost::posix_time::ptime> >::cancel(boost::asio::detail::deadline_timer_service<boost::asio::time_traits<boost::po
six_time::ptime> >::implementation_type&, boost::system::error_code&) /usr/include/boost/asio/deadline_timer_service.hpp:96 …
=> Fix a data race in GbpOpflexServer - protect prr_timer with mutex

agent-ovs/lib/AgentLogHandler.cpp, agent-ovs/lib/logging.cpp, agent-ovs/opflex-agent-ovs.conf.in, libopflex/comms/ActivePeer.cpp, libopflex/comms/ActiveTcpPeer.cpp, libopflex/comms/CommunicationPeer.cpp, libopflex/comms/active_connection.cpp, libopflex/comms/common.cpp, libopflex/comms/include/yajr/rpc/methods.hpp, libopflex/comms/loopdata.cpp, libopflex/comms/passive_listener.cpp, libopflex/comms/peer.cpp, libopflex/comms/test/comms_test.cpp, libopflex/comms/transport/PlainText.cpp, libopflex/comms/transport/ZeroCopyOpenSSL.cpp, libopflex/cwrapper/ofloghandler.cpp, libopflex/cwrapper/test/cwrapper_test.cpp, libopflex/engine/MOSerializer.cpp, libopflex/engine/Processor.cpp, libopflex/engine/test/main.cpp, libopflex/include/opflex/c/ofloghandler_c.h, libopflex/include/opflex/logging/OFLogHandler.h, libopflex/logging/include/opflex/logging/internal/logging.hpp
This matches the levels defined in agent-ovs
Existing logs have been remapped
DEBUG3/DEBUG4 -> TRACE
DEBUG1/DEBUG2 -> DEBUG
=> Reducing the number of supported logging levels in libopflex

libopflex/engine/OpflexListener.cpp, libopflex/engine/OpflexServerConnection.cpp, libopflex/engine/include/opflex/engine/internal/OpflexServerConnection.h
- removing connection mutex lock in sendToOne() to remove order dependency
- protecting reference vectors using a new mutex instead of uri_map_mutex
=> Fix for lock order inversion between uri_map_mutex and conn_mutex

libopflex/engine/Processor.cpp
These are unnecessarily polluting the logs and adding no value
=> Suppress purging logs for observables

agent-ovs/cmd/test/framework_stress.cpp, agent-ovs/lib/include/opflexagent/test/BaseFixture.h, agent-ovs/lib/test/EndpointManager_test.cpp, libopflex/modb/test/TestListener.h
usleep - This C routine is considered obsolete (as opposed to the shell command by the same name). The interaction of this function with SIGALRM and other timer functions such as sleep(), alarm(), setitimer(), and nanosleep() is unspecified (CWE-676).
=> Address codacity warnings: convert all usleep to nanosleep

agent-ovs/lib/AgentPrometheusManager.cpp, agent-ovs/lib/EndpointManager.cpp, agent-ovs/lib/FSEndpointSource.cpp, agent-ovs/lib/ModelEndpointSource.cpp, agent-ovs/lib/include/opflexagent/Endpoint.h, agent-ovs/lib/include/opflexagent/PrometheusManager.h, agent-ovs/lib/test/EndpointManager_test.cpp
- nested VM have multiple interfaces. Since we annotate only with "vm-name", there is duplication of EP metrics.
- duplication is not expected to happen in k8s setups since (name,namespace) are supposed to be unique.
- To address this only in openstack setup, "neutron-network" presence is checked in EP file; EP name is tagged as additional annotation to avoid duplication.
- make check changes done and manually tested in build VM
- cleaned up duplicate metric logging
- TBD: similar changes have to be done in nested VMs on ESX. (change expected only in FSEndpointSource). This will be tracked with a separate issue.
=> Address duplicate metric issues in OpenShift on OpenStack setup

agent-ovs/ovs/PacketDecoder.cpp, agent-ovs/ovs/PacketDecoderLayers.cpp, agent-ovs/ovs/test/PacketDecoder_test.cpp
Ip options are currently not recognized, do not return error in this
case. Avoid including brackets in strings, as this seems to cause
errors in json parsing.Fix parsing of qtag
=> Fix error logs in droplog

agent-ovs/ovs/PacketDecoderLayers.cpp, agent-ovs/ovs/include/PacketDecoderLayers.h, agent-ovs/ovs/test/PacketDecoder_test.cpp
Correct print arguments after qtag fix.
(cherry picked from commit 3b53f37a7db3a013d2b16dc4c1e901b34b311734)
=> Fix previous commit

agent-ovs/Makefile.am, agent-ovs/lib/include/opflexagent/PrometheusManager.h, agent-ovs/server/ServerPrometheusManager.cpp, agent-ovs/server/StatsIO.cpp, agent-ovs/server/test/AgentStats_test.cpp
- integration with prometheus
- macke check integration as part of agent_test
- TODO:
- OFAgent/OFServerStats today dont get freed up on connection restart. Will be addressed next.
- Readme and grafana to be updated
Sample curl output:
opflex_agent_identity_req_count{agent="127.0.0.1:9999"} 1.000000
opflex_agent_policy_update_count{agent="127.0.0.1:9999"} 1.000000
opflex_agent_policy_unavailable_resolve_count{agent="127.0.0.1:9999"} 1.000000
opflex_agent_policy_resolve_count{agent="127.0.0.1:9999"} 1.000000
opflex_agent_policy_resolve_err_count{agent="127.0.0.1:9999"} 0.000000
=> Support for agent specific prometheus metrics in opflex-server

agent-ovs/ovs/PacketLogHandler.cpp, agent-ovs/ovs/include/PacketLogHandler.h
With IPv6 packets, 10 packet events exceed 4k boundary slightly at
4310 bytes, this causes json parsing errors in host-agent, increase to
8k.Also increase packet capture size, incase a jumbo packet is captured
to 12k.
TODO: Will add test coverage
(cherry picked from commit d58d5f6259cf40ed704eaf12198d5a508b02322b)
=> Fix buffer truncation issue

agent-ovs/lib/AgentPrometheusManager.cpp, agent-ovs/lib/include/opflexagent/PrometheusManager.h, agent-ovs/lib/include/opflexagent/test/BaseFixture.h, agent-ovs/lib/test/ServiceManager_test.cpp, agent-ovs/ovs/PolicyStatsManager.cpp, agent-ovs/ovs/test/ContractStatsManager_test.cpp, agent-ovs/server/ServerPrometheusManager.cpp, agent-ovs/server/StatsIO.cpp, agent-ovs/server/test/AgentStats_test.cpp
- Remove these objects from modb and prometheus if these connection stats arent found
- Move one of the apis to BaseFixture so that its reused across agent and server tests
- Make check integration
=> Remove OFAgent/ServerStats objects from MoDB when connection is removed

agent-ovs/lib/AgentPrometheusManager.cpp, agent-ovs/lib/include/opflexagent/PrometheusManager.h, agent-ovs/lib/test/ServiceManager_test.cpp, agent-ovs/ovs/test/ServiceStatsManager_test.cpp, agent-ovs/server/ServerPrometheusManager.cpp
- svc metrics get annotated with name, namespace and scope. multiple svc files get created with these same annotations but with varying service-ip.
- tagging svc metrics with uuid to avoid the clash. (not using svc-ip since service mapping is a list and there could be multiple service ips within a service file)
- reducing duplicate metric logging per family instead of each metric in the family
- changing ERROR to WARNING within PrometheusManager
- make check integration
Sample metrics:
opflex_svc_rx_packets{name="kube-dns",namespace="kube-system",scope="cluster",uuid="dc3b8d25-92b8-4b98-bbf6-1d4e0317b00f"} 0.000000
opflex_svc_rx_packets{name="kubernetes",namespace="default",scope="cluster",uuid="0cc822c8-ec23-43e2-870d-627083117ff0"} 0.000000 …
=> Addressing dup svc metrics seen in OpenShift on OpenStack

libopflex/comms/loopdata.cpp
Since destroying is an atomic now it's visible to other
threads sooner resulting in the walk sometimes happening
before the close has completed. The handles that aren't
closed are logged on each cycle
=> Remove assert in walkAndCount cb

agent-ovs/lib/TunnelEpManager.cpp, agent-ovs/lib/include/opflexagent/TunnelEpManager.h
WARNING: ThreadSanitizer: data race (pid=28641)
Read of size 1 at 0x7b1000012ad0 by thread T11:
#8 opflexagent::TunnelEpManager::on_timer(boost::system::error_code const&) lib/TunnelEpManager.cpp:172 (libopflex_agent.so.0+0x243cff)
Previous write of size 1 at 0x7b1000012ad0 by main thread (mutexes: write M180):
#4 opflexagent::TunnelEpManager::stop() lib/TunnelEpManager.cpp:88 (libopflex_agent.so.0+0x24393e)
#5 opflexagent::OVSRenderer::stop() ovs/OVSRenderer.cpp:285 (libopflex_agent_renderer_openvswitch.so+0xcb84b)
#6 opflexagent::Agent::stop() lib/Agent.cpp:718 (libopflex_agent.so.0+0x2723d8)
#7 AgentLauncher::run() cmd/opflex_agent.cpp:128 (opflex_agent+0x3a4a7)
#8 main cmd/opflex_agent.cpp:322 (opflex_agent+0x16dc2)
Location is heap block of size 64 at 0x7b1000012ac0 allocated by main …
=> Protecting timer with a mutex

agent-ovs/cmd/test/policy_repo_stress.cpp, agent-ovs/lib/SimStats.cpp, agent-ovs/lib/include/opflexagent/SimStats.h, agent-ovs/ovs/AdvertManager.cpp, agent-ovs/ovs/InterfaceStatsManager.cpp, agent-ovs/ovs/include/InterfaceStatsManager.h
WARNING: ThreadSanitizer: data race (pid=18054)
Read of size 1 at 0x7b1000014d90 by thread T11:
#8 opflexagent::InterfaceStatsManager::on_timer(boost::system::error_code const&) ovs/InterfaceStatsManager.cpp:105 (libopflex_agent_renderer_openvswitch.so+0x1e74e1)
#14 operator() lib/Agent.cpp:605 (libopflex_agent.so.0+0x275439)
#15 __invoke_impl<void, opflexagent::Agent::start()::<lambda()> > /usr/include/c++/9/bits/invoke.h:60 (libopflex_agent.so.0+0x275439)
#16 __invoke<opflexagent::Agent::start()::<lambda()> > /usr/include/c++/9/bits/invoke.h:95 (libopflex_agent.so.0+0x275439)
#17 _M_invoke<0> /usr/include/c++/9/thread:244 (libopflex_agent.so.0+0x275439)
#18 operator() /usr/include/c++/9/thread:251 (libopflex_agent.so.0+0x275439)
#19 _M_run /usr/include/c++/9/thread:195 …
=> Protecting few deadline timers with mutex

agent-ovs/ovs/JsonRpcRenderer.cpp, agent-ovs/ovs/NetFlowRenderer.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/QosRenderer.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/SwitchManager.cpp, agent-ovs/ovs/include/JsonRpcRenderer.h, agent-ovs/ovs/include/OVSRenderer.h, agent-ovs/ovs/include/SwitchManager.h
WARNING: ThreadSanitizer: data race (pid=4830)
Read of size 1 at 0x7b100000e050 by thread T11:
#7 opflexagent::SwitchManager::onConnectTimer(boost::system::error_code const&) ovs/SwitchManager.cpp:162 (libopflex_agent_renderer_openvswitch.so+0x1c4aa4)
#13 operator() lib/Agent.cpp:605 (libopflex_agent.so.0+0x2755d9)
Previous write of size 1 at 0x7b100000e050 by main thread (mutexes: write M180):
#4 opflexagent::SwitchManager::stop() ovs/SwitchManager.cpp:72 (libopflex_agent_renderer_openvswitch.so+0x1c4a06)
#5 opflexagent::OVSRenderer::stop() ovs/OVSRenderer.cpp:274 (libopflex_agent_renderer_openvswitch.so+0xcbdda)
#6 opflexagent::Agent::stop() lib/Agent.cpp:718 (libopflex_agent.so.0+0x273508)
#7 AgentLauncher::run() cmd/opflex_agent.cpp:128 (opflex_agent+0x3a4a7)
#8 main …
=> Protecting all remaining deadline timers

agent-ovs/ovs/FlowConstants.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/include/FlowConstants.h, agent-ovs/ovs/test/IntFlowManager_test.cpp, genie/MODEL/SPECIFIC/EPR/inventory.mdl
- CSR is a proxy vxlan gateway to on-prem with limited number of tunnels
- depending on the max tunnels, n nodes will have connectivity to csr
- each would load balance across the CSRs in that list
- the list comes as a remote-ep with nextHopLinks
- Nodes with no access to CSR use the same remote-ep format but
their next hop links will be list of nodes with CSR access
- The node with CSR access will bounce the traffic to the CSR using
its own load balancing algorithm
- In the reverse direction the node will bounce the traffic back to
the node which hosts the pod (based on the inner dest ip)
- The CSR does not know which node has which pod, so it uses ECMP
to send return traffic to one of the nodes it has tunnel with.
- This node will process the packet like it belonged to it and when
it …
=> CSR integration

agent-ovs/lib/QosManager.cpp, agent-ovs/lib/include/opflexagent/QosListener.h, agent-ovs/lib/include/opflexagent/QosManager.h, agent-ovs/lib/test/QosManager_test.cpp, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/ActionBuilder.cpp, agent-ovs/ovs/include/AccessFlowManager.h, agent-ovs/ovs/include/ActionBuilder.h, agent-ovs/ovs/include/ovs-shim.h, agent-ovs/ovs/ovs-shim.c, agent-ovs/ovs/test/AccessFlowManager_test.cpp, agent-ovs/ovs/test/include/FlowManagerFixture.h
Reverts noironetworks/opflex#258
One of the tests is failing inconsistently. 
2020-Sep-26 22:18:11.074616] [info] [lib/QosManager.cpp:383:updateQosConfigState] Requirement URI: /PolicyUniverse/PolicySpace/test/QosRequirement/req1/
[2020-Sep-26 22:18:11.074783] [info] [lib/QosManager.cpp:400:updateQosConfigState] Egress URI: /PolicyUniverse/PolicySpace/test/QosBandwidthLimit/testQos/
lib/test/QosManager_test.cpp(246): error: in "QosManager_test/verify_artifacts": check (checkQosDscpMarking(agent.getQosManager().getDscpMarking("veth0-acc"), dscpCfg)) has failed.
Please fix this and resubmit
=> Revert "Handle dscp config in QosManager."

agent-ovs/lib/FSEndpointSource.cpp, agent-ovs/lib/FSExternalEndpointSource.cpp, agent-ovs/lib/include/opflexagent/Endpoint.h, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/include/FlowConstants.h, agent-ovs/ovs/test/AccessFlowManager_test.cpp
This commit reverts
- commit 656ae3e5801e0b3b470d00a08f6ac643d7930f44
Author: Madhu Challa <challa@gmail.com>
Date:   Wed Apr 29 22:27:38 2020 -0700
Add a new flag access-allow-untagged
- commit 0b36f41be40b4ca4c9d2e82cdb844d12986543a6
commit 0b36f41be40b4ca4c9d2e82cdb844d12986543a6
Author: Madhu Challa <challa@gmail.com>
Date:   Fri Feb 28 16:28:08 2020 -0800
Permit untagged traffic for access-interface-vlan
These are no longer needed for openshift to work.
=> Revert openshift hack to dup untagged packets

agent-ovs/lib/FSEndpointSource.cpp, agent-ovs/lib/test/EndpointManager_test.cpp, agent-ovs/lib/test/QosManager_test.cpp
Per ep, there can be only 1 qos  policy. FSEndpointSource should  read qos-policy as 1 dictionary instead of list of dictionaries.
=> FSEndpointSource: Read qos-policy as a dict.

agent-ovs/ovs/AdvertManager.cpp, agent-ovs/ovs/IntFlowManager.cpp
Since we dont have a flag for overlay mode in opflex-agent,
turn off tunnel-advertisements based on missing uplink config.
Fix error in checking return value of if_nametoifindex syscall.
=> Disable Tunnel advertisements in overlay mode

agent-ovs/cmd/gbp_inspect.cpp
=> Avoid gbp_inspect crash when invalid options are used

agent-ovs/ovs/AdvertManager.cpp, agent-ovs/ovs/IntFlowManager.cpp
Since we dont have a flag for overlay mode in opflex-agent,
turn off tunnel-advertisements based on missing uplink config.
Fix error in checking return value of if_nametoifindex syscall.
=> Disable Tunnel advertisements in overlay mode (#276)

agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/include/opflexagent/PolicyManager.h, agent-ovs/lib/include/opflexagent/test/ModbFixture.h, agent-ovs/ovs/test/IntFlowManager_test.cpp
First commit has the model changes for ordering the classifiers within a rule. The priorities are assigned to the classifiers with reference to leaf side expectations. If any corner cases are not covered, let me know.
=> Sorting the classifiers on contracts with same range

agent-ovs/lib/FSEndpointSource.cpp, agent-ovs/lib/include/opflexagent/Endpoint.h, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/include/AccessFlowManager.h, agent-ovs/ovs/test/AccessFlowManager_test.cpp
- Connection tracking in security groups will drop the mirrored
ingress packet unless ingress rules are configured and its non
intuitive to add ingress allow for just this case.
- Bypass done via a separate table right after drop log table=0
whenever the src and dst pairs match service ip and its backend ip
- This is done so that later conntrack code can skip this table
when recirculating and secondly we only need to populate output
register for this case.
- In order to avoid the complexity of subscribing to service updates
and the ordering of svc and ep updates a new section is added
to the EP file "service-ip" an array of services the ep is
a backend to.
- We use these ips to populate the flows with a uuid of the ep
that will change as the ep file changes.
- Host agent will populate …
=> Bypass secgrp when backend reaches its service

agent-ovs/lib/FSEndpointSource.cpp, agent-ovs/lib/include/opflexagent/Endpoint.h, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/include/AccessFlowManager.h, agent-ovs/ovs/test/AccessFlowManager_test.cpp
- Connection tracking in security groups will drop the mirrored
ingress packet unless ingress rules are configured and its non
intuitive to add ingress allow for just this case.
- Bypass done via a separate table right after drop log table=0
whenever the src and dst pairs match service ip and its backend ip
- This is done so that later conntrack code can skip this table
when recirculating and secondly we only need to populate output
register for this case.
- In order to avoid the complexity of subscribing to service updates
and the ordering of svc and ep updates a new section is added
to the EP file "service-ip" an array of services the ep is
a backend to.
- We use these ips to populate the flows with a uuid of the ep
that will change as the ep file changes.
- Host agent will populate …
=> Bypass secgrp when backend reaches its service (#287)

agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/include/opflexagent/test/ModbFixture.h, agent-ovs/ovs/FlowUtils.cpp, agent-ovs/ovs/test/AccessFlowManager_test.cpp, genie/MODEL/SPECIFIC/GBP/COMMON/action.mdl
if we are able to resolve LogAction from the policyManager, that indicates that the agent is able to resolve the LogAction from the leaf(if it is set). we can just assign ruleLog=true and discard "ruleLog = resloveLog.get()->getLog(0) != 0 ;"
=> minor Logaction changes on PolicyManager side

agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/QosRenderer.cpp, agent-ovs/ovs/include/OvsdbState.h, agent-ovs/ovs/test/QosRenderer_test.cpp
Unreferenced  QoS and Queue records are not automatically destroyed. This change set takes care of deleting existing  qos/queue entry before creating new records.
Reference: http://www.openvswitch.org//support/dist-docs/ovs-vsctl.8.txt
=> Delete Qos and queue entry from ovsdb.

agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/PolicyStatsManager.cpp, agent-ovs/ovs/ServiceStatsManager.cpp, agent-ovs/ovs/SwitchManager.cpp, agent-ovs/ovs/include/IntFlowManager.h, agent-ovs/ovs/include/PolicyStatsManager.h, agent-ovs/ovs/include/SwitchManager.h
- Created a new thread to handle svc stat flows CRUD. The thread works on a new asio io_service object to handle new events from taskqueue.
- Stats collection done via ServiceStatsManager also uses the new asio io_service.
- All linux threads by default have SCHED_OTHER scheduling policy. This has a static priority of 0. Other sched policies like SCHED_FIFO and SCHED_RR allow users to control thread priority varying from values 1 to 99. Due to this FIFO/RR will preempt SCHED_OTHER threads. Either we move all threads to FIFO/RR and set priorities or somehow influence priority within SCHED_OTHER policy. Luckily there is a "nice" value than is configurable at a thread level per process which can control the total time allocated per thread. The new thread has highest "nice" value, which makes …
=> Changes to move svc stats to a separate thread

agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/PolicyStatsManager.cpp, agent-ovs/ovs/ServiceStatsManager.cpp, agent-ovs/ovs/SwitchManager.cpp, agent-ovs/ovs/include/IntFlowManager.h, agent-ovs/ovs/include/PolicyStatsManager.h, agent-ovs/ovs/include/SwitchManager.h
- Created a new thread to handle svc stat flows CRUD. The thread works on a new asio io_service object to handle new events from taskqueue.
- Stats collection done via ServiceStatsManager also uses the new asio io_service.
- All linux threads by default have SCHED_OTHER scheduling policy. This has a static priority of 0. Other sched policies like SCHED_FIFO and SCHED_RR allow users to control thread priority varying from values 1 to 99. Due to this FIFO/RR will preempt SCHED_OTHER threads. Either we move all threads to FIFO/RR and set priorities or somehow influence priority within SCHED_OTHER policy. Luckily there is a "nice" value than is configurable at a thread level per process which can control the total time allocated per thread. The new thread has highest "nice" value, which makes …
=> Changes to move svc stats to a low prio thread

agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/PolicyStatsManager.cpp, agent-ovs/ovs/ServiceStatsManager.cpp, agent-ovs/ovs/SwitchManager.cpp, agent-ovs/ovs/include/IntFlowManager.h, agent-ovs/ovs/include/PolicyStatsManager.h, agent-ovs/ovs/include/SwitchManager.h
Some flow programming problems have been reported with this change.
Reverting from the jefferson branch for now. We'll reenable once we
root cause the issue
Reverts noironetworks/opflex#297
=> Revert "Changes to move svc stats to a low prio thread"

agent-ovs/lib/EndpointManager.cpp, agent-ovs/lib/include/opflexagent/EndpointManager.h, agent-ovs/ovs/IntFlowManager.cpp
Pattern1:
WARNING: ThreadSanitizer: data race (pid=23522)
Write of size 8 at 0x7fff79e44c50 by thread T13 (mutexes: write M1028):
#0 std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<opflexagent::Endpoint
#1 std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::shared_ptr<opflexagent::Endpoint
#2 std::__detail::_Map_base<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > …
=> Fix tsan issues found during ep add/del and svc add/del in loop

agent-ovs/cmd/opflex_agent.cpp, agent-ovs/opflex-agent-ovs.conf.in, agent-ovs/ovs/OvsdbConnection.cpp
Peer cleanup happens automatically when the uv loop
is shutdown.
Cleanup codacy, clang-tidy issues in opflex_agent.cpp
Fix copy pasted comments in agent config
=> Address TSAN issue in OVSDB shutdown + other cleanups

agent-ovs/lib/IdGenerator.cpp, agent-ovs/ovs/ContractStatsManager.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/SecGrpStatsManager.cpp, agent-ovs/ovs/ServiceStatsManager.cpp, agent-ovs/ovs/TableDropStatsManager.cpp
1) Triangular deadlock
Scenario:
Svc Stats thread:
Holds switch manager mutex (sm_mutex) and sends barrier message to OVS and is stuck to get a response.
CondVar needs to be notified by sw connection thread.
Due to this all flow CRUD stalls.
Agent thread:
During contract/table-drop timer kickoff, it holds pstatMtx (to protect while going through all tables and collects stats from flows).
It is blocked while trying to acquire switch manager mutex.... (which is needed to protect flow writes)
Switch Connection thread:
Tries to acquire pstatMtx during stats response, and is stuck
It wont be able to send condVar notify to unblock svc stats thread since it doesnt get a chance to service barrier response.....
Fix:
Unfortunately not detected by tsan. The fix is to break the cycle by making the …
=> Fix more data race issues

agent-ovs/lib/EndpointManager.cpp
WARNING: ThreadSanitizer: data race (pid=29448)
Write of size 8 at 0x7b4400040100 by thread T16 (mutexes: write M1154):
#0 operator delete(void*) <null> (libtsan.so.0+0x75b31)
#1 std::_Hashtable<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, opflexagent::EndpointManager::EndpointState>, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, opflexagent::EndpointManager::EndpointState> >, std::__detail::_Select1st, std::equal_to<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::hash<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, …
=> Protect ep_map while updating ep counters

agent-ovs/ovs/IntFlowManager.cpp
Issue was happening once every few runs. But then it became unreproducible due to the way threads were scheduled. Tried 25+ times with the fix and things look good.
Description:
- SNAT/DNAT flows will be programmed initially from higher prio Agent thread.
- Low prio Svc Stats thread today programs the flows with stats cookies
later on so that snat/dnat flows become eventually consistent to correlate stats.
- In case svc gets deleted, then agent io thread will delete svc flows immediately.
Since svc stats thread is low priority, it could be in the process of updating
SNAT/DNAT flows after agent thread deleted SNAT/DNAT flows. This can lead to
stale snat/dnat flow entries for that svc.
- To avoid these stale entries, call programServiceSnatDnatFlows() for the deleted
svc so that the stale …
=> Fix stale entries seen after deletion of service during make check tests

agent-ovs/lib/AgentPrometheusManager.cpp, agent-ovs/lib/EndpointManager.cpp, agent-ovs/lib/include/opflexagent/EndpointManager.h, agent-ovs/lib/include/opflexagent/PolicyManager.h, agent-ovs/lib/include/opflexagent/PrometheusManager.h, agent-ovs/lib/include/opflexagent/ServiceManager.h, agent-ovs/lib/test/EndpointManager_test.cpp, agent-ovs/lib/test/ServiceManager_test.cpp, agent-ovs/ovs/PolicyStatsManager.cpp, agent-ovs/ovs/include/PolicyStatsManager.h, agent-ovs/ovs/test/ContractStatsManager_test.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp, genie/MODEL/SPECIFIC/OBSERVER/modbcounts.mdl
- Added support for modb counts per object type for few objects. More object counts can be added in future.
- Updated MoDBCount MO with what we display now.
- Removed redundant active_ep_count and active_svc_count.
- did some misc cleanup.
- added tests for modb counts
TODO:
Move OFPeer and MoBDCount updates to a new class (currently under PolicyStatsManager)
Remove created/removed counts of EP and SVC - customers can just use total ep and svc counts instead
Update Readme for new metrics
Update grafana db templates
Remove HAVE_PROMETHEUS_SUPPORT #define and configuration from agent
=> Support for modb counts in opflex-agent

agent-ovs/lib/EndpointManager.cpp, libopflex/engine/OpflexPool.cpp, libopflex/engine/include/opflex/engine/internal/OpflexPool.h, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/ofcore/OFFramework.cpp
Existing peers are closed asynchronously so disconnects
might be processed after the call to readd the configured
peers. In some cases this resulted in an agent with no peers.
Restarting the agent was the only way to recover
Changing to disconnect the learned peers only. Configured
peers do not need to be disconnected
=> Reset learned peers only when server triggers fallback

agent-ovs/lib/EndpointManager.cpp, libopflex/engine/OpflexPool.cpp, libopflex/engine/include/opflex/engine/internal/OpflexPool.h, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/ofcore/OFFramework.cpp
Existing peers are closed asynchronously so disconnects
might be processed after the call to readd the configured
peers. In some cases this resulted in an agent with no peers.
Restarting the agent was the only way to recover
Changing to disconnect the learned peers only. Configured
peers do not need to be disconnected
=> Reset learned peers only when server triggers fallback (#349)

libopflex/comms/CommunicationPeer.cpp, libopflex/comms/transport/PlainText.cpp
nread is an unsigned value and was overflowing causing
buffer read issues
add null terminator at end only if full msg has been read
=> Avoid invalid read when buffer is full

libopflex/comms/CommunicationPeer.cpp, libopflex/comms/transport/PlainText.cpp
nread is an unsigned value and was overflowing causing
buffer read issues
add null terminator at end only if full msg has been read
=> Avoid invalid read when buffer is full (#351)

agent-ovs/debian/control, agent-ovs/rpm/opflex-agent.spec.in
=> Fix min prometheus-cpp version required for deb/rpm builds

agent-ovs/Makefile.am, agent-ovs/lib/test/PolicyManager_test.cpp, agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/include/DnsManager.h, agent-ovs/ovs/test/DnsManager_test.cpp, genie/MODEL/SPECIFIC/EPR/epdr.mdl
As of now this is not a wheel timer.
Dns timer runs every 1 secs and expires entries
and updates related resolves.
TODO:
Convert to a wheel timer to handle scale.
=> Add DNS expiry timer

agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/include/DnsManager.h, agent-ovs/ovs/include/ip.h, agent-ovs/ovs/test/AccessFlowManager_test.cpp, agent-ovs/ovs/test/DnsManager_test.cpp
Recursive resolution is not typically required for hosts.
Will add support if we find we need it.
=> Add DNS v6 record processing.

agent-ovs/ovs/test/AccessFlowManager_test.cpp
With the same rule priorities, on RPM builds, flows are pushed
with a different order, which is fine, so force the priority
=> Fix RPM build

agent-ovs/lib/FSServiceSource.cpp, agent-ovs/lib/Service.cpp, agent-ovs/lib/include/opflexagent/Service.h, agent-ovs/ovs/FlowBuilder.cpp, agent-ovs/ovs/FlowExecutor.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/TableState.cpp, agent-ovs/ovs/include/FlowBuilder.h
client-ip affinity with a specified timeout ensures the same client
goes to the same backend using a hash on the nw_src field.
The above flow will be added at a higher prio than the regular 5 tuple
hash flow.
by using hard_timeout we ensure this flow is deleted by ovs once
timeout is reached at which affinity goes away and we start using
5 tuple hash from then on
affinity flow
cookie=0x0, duration=14.224s, table=5, n_packets=0, n_bytes=0, hard_timeout=30, priority=51,ip,reg6=0xb,nw_dst=169.254.169.254 actions=set_field:00:22:bd:f8:19:ff->eth_src,set_field:e2:35:f9:9e:2c:3b->eth_dst,multipath(nw_src,1024,iter_hash,1,32,NXM_NX_REG7[]),goto_table:6
regular flow
cookie=0x0, duration=14.224s, table=5, n_packets=0, n_bytes=0, priority=50,ip,reg6=0xb,nw_dst=169.254.169.254 …
=> Add session-affinity for services

agent-ovs/lib/FSServiceSource.cpp, agent-ovs/lib/Service.cpp, agent-ovs/lib/include/opflexagent/Service.h, agent-ovs/ovs/FlowBuilder.cpp, agent-ovs/ovs/FlowExecutor.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/TableState.cpp, agent-ovs/ovs/include/FlowBuilder.h
client-ip affinity with a specified timeout ensures the same client
goes to the same backend using a hash on the nw_src field.
The above flow will be added at a higher prio than the regular 5 tuple
hash flow.
by using hard_timeout we ensure this flow is deleted by ovs once
timeout is reached at which affinity goes away and we start using
5 tuple hash from then on
affinity flow
cookie=0x0, duration=14.224s, table=5, n_packets=0, n_bytes=0, hard_timeout=30, priority=51,ip,reg6=0xb,nw_dst=169.254.169.254 actions=set_field:00:22:bd:f8:19:ff->eth_src,set_field:e2:35:f9:9e:2c:3b->eth_dst,multipath(nw_src,1024,iter_hash,1,32,NXM_NX_REG7[]),goto_table:6
regular flow
cookie=0x0, duration=14.224s, table=5, n_packets=0, n_bytes=0, priority=50,ip,reg6=0xb,nw_dst=169.254.169.254 …
=> Add session-affinity for services (#369)

agent-ovs/cmd/test/Policies.cpp, agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/test/PolicyManager_test.cpp, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/FlowConstants.cpp, agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/include/DnsManager.h, agent-ovs/ovs/include/FlowConstants.h, agent-ovs/ovs/test/AccessFlowManager_test.cpp, agent-ovs/ovs/test/include/FlowManagerFixture.h
Register packetin handler for access bridge.
Avoid duplicate packet punting by adding a metadata flag for direction
in access bridge.
EGRESS_DIR -> from ep
INGRESS_DIR -> to ep
Skip programming DNS rules till atleast one name in the set is resolved,
otherwise all ip/v6 flows will be allowed till first DNS name in rule is resolved.
Fix LGTM warning.
=> Fix PacketIn for Access Bridge

agent-ovs/lib/EndpointManager.cpp
There are 2 ways to delete a remoteIp
1. send update / replace for the remoteEp without the remoteIp
Is handled correctly because the notif code gets the correct
remoteEp Mo which then triggers the remoteEp update
2. delete the remoteIp alone
This case is not handled today. there is no listener to this update
so no notif happens.
Based on the logs CSCvx60417 / 	690770038 this is whats happening here.
This is normally not an issue if the same remoteIp is updated later,
in this case the remoteIp is a VIP. But if the VIP to VTEP mapping
changes and update does not come through we end up with a flow
for the VIP thats using a stale VTEP.
This fix ensures we handle this case and delete the stale flow
right away, any time you see this log
[2021-Mar-25 22:41:12.968729] [debug] …
=> handle remoteIp delete properly

agent-ovs/lib/EndpointManager.cpp
There are 2 ways to delete a remoteIp
1. send update / replace for the remoteEp without the remoteIp
Is handled correctly because the notif code gets the correct
remoteEp Mo which then triggers the remoteEp update
2. delete the remoteIp alone
This case is not handled today. there is no listener to this update
so no notif happens.
Based on the logs CSCvx60417 / 	690770038 this is whats happening here.
This is normally not an issue if the same remoteIp is updated later,
in this case the remoteIp is a VIP. But if the VIP to VTEP mapping
changes and update does not come through we end up with a flow
for the VIP thats using a stale VTEP.
This fix ensures we handle this case and delete the stale flow
right away, any time you see this log
[2021-Mar-25 22:41:12.968729] [debug] …
=> handle remoteIp delete properly (#373)

agent-ovs/ovs/DnsManager.cpp
Issue seen with Ubuntu 21.04 and gcc 10.3
=> Need to explicitly reference placeholder namespace with latest gcc

agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp
This is a rework of
https://github.com/noironetworks/opflex/commit/aee03cc208f2733cae3a35478db6d36570baade7
By giving nat flows +1 prio, does not fully solve the problem.
we can have another routed prefix that would fall at the same
priority as the nat one and if the subnets are overlapping the
packets would take the non nat path.
In bosch they had
nw_dst=10.128.0.0/9 non-nat
nw_dst=10.0.0.0/9 non-nat
nw_dst=10.0.0.0/8 nat
with current code this would result in all the 3 flows to use prio=159 which
makes it non deterministic and back to the original problem we had.
I took this approach initially because we did not have a big enough hole
for all the priorities esp for v6.
But since it does not work the fix considered 2 designs
- assign nat priorities dynamically based on subnet/prefix of …
=> Fix nat rules priority across all routed prefixes.

agent-ovs/ovs/DnsManager.cpp
RHEL7 still ships with boost 1.53 which doesn't have boost::placeholder
and puts it in the unnamed namespace. Using boost:arg is supported with
both older and newer boost versions
=> Use boost:arg instead of boost::placeholder to build on older boost

agent-ovs/lib/Agent.cpp, agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/opflex-agent-ovs.conf.in, agent-ovs/ovs/OvsdbConnection.cpp, libopflex/comms/CommunicationPeer.cpp, libopflex/engine/OpflexClientConnection.cpp, libopflex/engine/OpflexPEHandler.cpp, libopflex/engine/OpflexServerConnection.cpp, libopflex/engine/include/opflex/engine/Processor.h, libopflex/engine/include/opflex/engine/internal/OpflexConnection.h, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/include/opflex/yajr/internal/comms.hpp, libopflex/include/opflex/yajr/yajr.hpp, libopflex/ofcore/OFFramework.cpp, libopflex/ofcore/test/OFFramework_test.cpp
Reduce default to 2 mins from 8 mins
=> Make peer keepalive timeout configurable

agent-ovs/Makefile.am, agent-ovs/debian/opflex-agent.dirs, agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/include/DnsManager.h, agent-ovs/ovs/include/OVSRenderer.h, agent-ovs/ovs/test/DnsManager_test.cpp, agent-ovs/plugin-renderer-openvswitch.conf.in, agent-ovs/rpm/opflex-agent.spec.in
Backup DNS entries on a host-mounted store
and restore on restart to prevent blackholing.
=> Restore DNS cache on reboot

agent-ovs/lib/Agent.cpp, agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/opflex-agent-ovs.conf.in, agent-ovs/ovs/OvsdbConnection.cpp, libopflex/comms/CommunicationPeer.cpp, libopflex/engine/OpflexClientConnection.cpp, libopflex/engine/OpflexPEHandler.cpp, libopflex/engine/OpflexServerConnection.cpp, libopflex/engine/include/opflex/engine/Processor.h, libopflex/engine/include/opflex/engine/internal/OpflexConnection.h, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/include/opflex/yajr/internal/comms.hpp, libopflex/include/opflex/yajr/yajr.hpp, libopflex/ofcore/OFFramework.cpp, libopflex/ofcore/test/OFFramework_test.cpp
Reduce default to 2 mins from 8 mins
=> Make peer keepalive timeout configurable (#390)

agent-ovs/ovs/DnsManager.cpp, agent-ovs/ovs/include/DnsManager.h, agent-ovs/ovs/test/DnsManager_test.cpp, genie/MODEL/SPECIFIC/EPR/epdr.mdl
Handle SRV record type for headless services
Refactor code to reduce redundancy.
Display Cname and SRV records in the MO
Process additional record section.
TODO: port argument from SRV needs to be added to policy flow
=> Handle Dns SRV Records

agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/test/IntFlowManager_test.cpp
To avoid logging flooded packets which are going to be dropped,
for broadcast packets on the service vlan, add an explicit drop
in the out table. Service vlan anyway does not have a flood list.
Tested with manual flow addition on local setup.
=> Drop flooded unhandled packets on service vlan

agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/FlowUtils.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/include/AccessFlowManager.h, agent-ovs/ovs/include/FlowUtils.h, agent-ovs/ovs/test/AccessFlowManager_test.cpp, agent-ovs/ovs/test/TableDropStatsManager_test.cpp
System security group is an operator level security group applicable for the entire OpenStack VMM - domain. This operator level / system level security group cannot be overridden by other security groups from the common and other tenants. The system security group rules can be fine-tuned further by other security group rules. 
This patch introduces two new tables  sys_ingress and sys_egress.  Packets which were directed to existing sg tables are directed (from Group_map table ) to these new tables. If they match any flow in system sg table, they are passed to existing sg tables. 
[sys_ingress]  --> [ingress]
[sys_egress]  --> [egress]
Stateful rules are supported in system sg. Packets are matched with different ct_state as done in the existing table, connections are committed in the …
=> System  security group  changes

agent-ovs/ovs/ContractStatsManager.cpp
Fix the incorrect array dereference leading to the crash
=> Fix out of bounds crash in bbva

agent-ovs/ovs/include/FlowConstants.h
This mask was introduced as part of fixing the punt of DNS packets
for the egress DNS feature. However the mask should be limited to 0x3
to avoid colliding with droplog metadata.
=> Reduce scope of direction mask for access flows

agent-ovs/lib/Agent.cpp, libopflex/Makefile.am, libopflex/comms/CommunicationPeer.cpp, libopflex/comms/active_connection.cpp, libopflex/include/opflex/yajr/async_doc_parser.hpp, libopflex/include/opflex/yajr/internal/comms.hpp
Allow parsing partial json messages. Invokes comms callback on parse complete and continues with the parse. Currently supports only one reader and writer per comms object. On error the callback disconnects and reconnects with the client there by preserving the sanity of the json stream.
Controlled via 2 env variables OPFLEX_USE_ASYNC_JSON for leaf <> opflex comms and OVS_USE_ASYNC_JSON for ovsdb <> opflex comms. The usage will be OPFLEX_USE_ASYNC_JSON= OVS_USE_ASYNC_JSON= <opflex command>, the same can be provided via docker env variables when running under docker. If neither env variable is present the code reverts to the old sync way of parsing that would fail if the json comes in partial chunks.
The env variables can be set via config as
"opflex": {
"asyncjson" : { "enabled" : "true" } …
=> Async Json Parser for Opflex and Ovs

agent-ovs/ovs/include/PacketLogHandler.h
Add some null checks for packet IP matching
=> Fix core while droplog pruning  non-IP packets

libopflex/comms/active_connection.cpp
Bosch wants no changes and this was a fix added along with async json parse, the feature itself is enabled under a config option, except the fix for the double free. So reverting this fix which if hit will cause opflex to crash and restart.
This revert is specific to this branch and master still has this fix.
=> Revert crash fix for kmr2

agent-ovs/cmd/opflex_agent.cpp, agent-ovs/lib/include/opflexagent/logging.h, agent-ovs/lib/logging.cpp, agent-ovs/ovs/PacketDecoderLayers.cpp, agent-ovs/ovs/PacketLogHandler.cpp, agent-ovs/ovs/test/PacketDecoder_test.cpp
1. Print src and dst mac as separate fields
2. Separate log file for drop_logs.
Configure droplog destination with command line arguments
--drop_log_file <file-name> --drop_log_syslog (in case sink is
syslog)
By default droplogs go to the opflex-agent log file.
=> Enhancements to droplog - part 1

.travis/install-dependencies.sh, agent-ovs/configure.ac, agent-ovs/debian/control, agent-ovs/lib/AgentPrometheusManager.cpp, agent-ovs/rpm/opflex-agent.spec.in, lgtm.yml
- 0.12.1 uses civetweb 1.13 that has a CVE - https://nvd.nist.gov/vuln/detail/CVE-2020-27304
- According to https://jfrog.com/blog/cve-2020-27304-rce-via-directory-traversal-in-civetweb-http-server/, the relevant CVE is fixed in civet web > 1.14
- latest prometheus-cpp version is 1.1.0, but that needs c++14.
- moving to prometheus-cpp 1.0.1 for now, which uses civetweb 1.15.
- updated configuration script to specify min dep version
- updated debs created and pushed to S3 for travis (thanks Tom)
- lgtm build updated
=> Move to prometheus-cpp 1.0.1

agent-ovs/lib/Agent.cpp, agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/opflex-agent-ovs.conf.in, libopflex/engine/Processor.cpp, libopflex/engine/include/opflex/engine/Processor.h, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/ofcore/OFFramework.cpp
The retry delay should be configurable, with a default initial backoff value of 10 seconds. This can be set to larger amounts for servers that crash under heavy loads from frequent re-requests.
=> Make policy retry delay configurable

libopflex/comms/transport/ZeroCopyOpenSSL.cpp
This was causing compilation issues on Ubuntu 22.04
=> Call ERR_load_SSL_strings only w/ OpenSSL < 1.1.0

agent-ovs/ovs/IntFlowManager.cpp
RPA had an ordering issue when local and remote eps are present with same uuid which are hit during vm migration.
The ordering in which local ep flows are broken is as follows
- remote ep with uuidA present
- local ep with same uuidA added
- remote ep with uuidA is deleted
This would cause local ep flows to be deleted as well because both got added with same uuid
The ordering issue should be prevented at the source itself so the ep file is deleted on src node, all remote eps updated, and then the ep file is created on the dst node. The extra cost with this solution is to check if the other type of ep exists when one is deleted.
somehow with the B series the second part, remote ep delete comes after the ep file is created on target.
For consistency also doing the same when a local ep is …
=> Make local / remote ep flow mods robust

libopflex/engine/Processor.cpp
Commit e5d0b8959adac24d4208179f65bc5f657015909f added dithering to the retry timeout, but introduced a bug: the base time gets included twice in the calculation, leading to double the intended timeout. This patch fixes that issue.
=> Fix retry dithering call

agent-ovs/lib/PolicyManager.cpp
These got uncovered with the previous fix when doing compares while an copy worked just fine.
Since master has them turned off we were not seeing these in master branch.
=> Fix uninitialized warnings in code.

libopflex/engine/Processor.cpp, libopflex/engine/test/Processor_test.cpp
If an MO reference is added locally, the refresh timeout for that MO is in most cases set to half the PRR, or 1 hour with the default timeout values. If the Processor invokes the OpflexPool's sendToRole handler before the peer has completed the identity request handshake, then the OpflexPool won't send the message, and the MO's timeout is unchanged. When the handshake does happen, the processor re-sends the policy resolve requests for those MOs, but it doesn't update the timeouts for those MOs. This can lead to excessive timeout values in some cases (e.g. request gets rejected with an error, even if the error state is short-lived).
This patch adds updates of the refresh time for the handshake succeeded callback, in order to avoid the excessive timeout described above.
=> Fix pre-handshake policy resolve refresh timeouts

agent-ovs/ovs/FlowUtils.cpp, agent-ovs/ovs/test/AccessFlowManager_test.cpp
icmp unreachable related flows do not have reply bit set. do not use the reply bit for related flows since its implicit and may not be set all the time.
(found by cisco IT)
=> Fix related flows

agent-ovs/ovs/FlowUtils.cpp, agent-ovs/ovs/test/AccessFlowManager_test.cpp
prev fix to ignore reply introduced a regression with masks. when related bit is set, ignore reply and established we do make sure connection is not new AND not invalid.
=> Fix related flow mask

.travis/install-dependencies.sh
The OpenSSL libraries need to be bumped for builds.
=> Bump OpenSSL version for builds

docker/travis/Dockerfile-opflex
This package installs /etc/pki/openssl11.cnf that can be selected at process startup time via OPENSSL_CONF env
For k8s it can be done via
image: challa/opflex:11
env:
- name: OPENSSL_CONF
value: "/etc/pki/openssl11.cnf"
The variable makes the openssl3 libs compatible with 1.1 If not set the behavior is same as openssl3
=> Add support for 1.1 compat with openssl 3.x

agent-ovs/debian/control
This was only needed in older ubuntu distros. In newer distros such as jammy, it causes build failures due to a missing dh-system dependency.
=> Remove dh-systemd

agent-ovs/cmd/opflex_agent.cpp, agent-ovs/ovs/include/PacketLogHandler.h, libopflex/include/opflex/yajr/async_doc_parser.hpp
- earlier fix for reset_opflex missed stop only condition
- handle exceptions in packetlogger when socket not connected that prevents the rest of the agent cleanups due to exception
- comment out creation of debug file for async json. The writes were commented out but realized I missed commenting out the file creation
verified that ctrl C consistently works now.
=> Cleanups for clean restart

agent-ovs/lib/Agent.cpp, agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/SwitchManager.cpp, agent-ovs/ovs/include/IntFlowManager.h
Mcast -
On startup agent will cache old values if present
in opflex-groups.json and start a timer to timeout these values. Until the timer expires new values
learned are merged with the old values and added
to the file. Eventually the timer will expire and
new values take effect from then on.
"timers": {
"mcast-cache-timeout": 600,
}
section in opflex-agent.conf controls the timeout
in seconds. Default is 300 secs or 5 mins
Switch-state-sync -
"timers": {
"switch-sync-delay": 300
}
This value was previous hardcoded to 5 seconds,
which is also the default. However it can be
changed via the above config option. It needs
to be increased if we anticipate many flows that
exist and a long delay between getting PlatformConfig Mo and the rest of the Mos that would be needed
to configure the new …
=> Add configurable timeouts for mcast and switch sync

agent-ovs/Makefile.am, agent-ovs/cmd/gbp_inspect.cpp, agent-ovs/cmd/test/mock_server.cpp, libopflex/engine/InspectorClientImpl.cpp, libopflex/engine/MOSerializer.cpp, libopflex/engine/include/opflex/engine/InspectorClientImpl.h, libopflex/engine/include/opflex/engine/internal/MOSerializer.h, libopflex/engine/test/MOSerialize_test.cpp, libopflex/include/opflex/ofcore/InspectorClient.h, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/ofcore/OFFramework.cpp, libopflex/ofcore/test/OFFramework_test.cpp
This is especially useful when dumping MODB
Another PR will be raised to make this more generic and support a list of class types to exclude instead of just observables
=> Add option to gbp_inspect to ignore all observables

agent-ovs/lib/EndpointManager.cpp, agent-ovs/ovs/OvsdbConnection.cpp, genie/src/main/java/org/opendaylight/opflex/genie/content/format/agent/structure/cpp/FClassDef.java, libopflex/engine/MOSerializer.cpp
Address some linter complaints
Avoid generating some unused code
=>  Fix logic issue in last change

.travis.yml, docker/travis/Dockerfile-opflex-build, docker/travis/Dockerfile-opflex-build-base
Fix grpc dep to 1.52.2
Attempt to reenable cache of grpc builds
Use -j2 when building in UBI env
Stop manually installing cmake. Upstream version is new enough now
=> Try to improve build times on Travis

agent-ovs/lib/Agent.cpp
This avoids timing issues where the config may not take effect
=> Move mcast & switch sync delay before renderer start

agent-ovs/lib/Agent.cpp, agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/opflex-agent-ovs.conf.in, agent-ovs/ovs/SwitchManager.cpp, agent-ovs/ovs/include/SwitchManager.h, libopflex/engine/OpflexPEHandler.cpp, libopflex/engine/OpflexPool.cpp, libopflex/engine/Processor.cpp, libopflex/engine/include/opflex/engine/Processor.h, libopflex/engine/include/opflex/engine/internal/OpflexPool.h, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/ofcore/OFFramework.cpp
Controlled via opflex.timers.switch-sync-dynamic default 0 secs
When configured > 0, in addition to the initial switch sync delay set via opflex.timers.switch-sync-delay (default 5 secs) agent will checking pending MOs not yet resolved and only when we have waited at least switch-sync-dynamic for each MO initiate the sync. Otherwise we will sleep for (switch-sync-dynamic - MO with least wait) and attempt another sync after that time.
The max retries = 5 is hardcoded, so after 5 checks if we still have pending MOs we will no longer wait. So the max additional wait (in addition to switch-sync-delay) will be switch-sync-dynamic * 5
This narrows the window where we are yet to resolve some MOs and prevents us from touching the flow tables till then.
Also changed all Sync logs from DEBUG to …
=> Dynamic switch sync delay

agent-ovs/lib/Agent.cpp, agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/opflex-agent-ovs.conf.in, libopflex/engine/MOSerializer.cpp, libopflex/engine/Processor.cpp, libopflex/engine/include/opflex/engine/Processor.h, libopflex/engine/include/opflex/engine/internal/MOSerializer.h, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/ofcore/OFFramework.cpp
"opflex": {
"startup": {
"policy-file": "/home/mchalla/thomas/pol.json",
"policy-duration": 0,
"resolve-aft-conn": false
},
- opflex.startup.policy-file contains pol.json to use at startup
- opflex.startup.policy-duration tells how long in seconds to keep resolving policy from the above pol.json
- opflex.startup.resolve-aft-conn wait till conn before using startup db use in combination with duration > 0
- opflex.startup.resolve-once placeholder for resolving only first time from startup db
- opflex.startup.full-proxy placeholder use startup db for life of opflex meaning startup db will be updated at run time to keep both in sync
If policy-file exists we create a startupdb thats used for intermediate resolves until the leaf connection succeeds based on the above startup-policy-duration
On …
=> Add support for coming up with a persist policy

.travis.yml, .travis/coveralls-deploy.sh, .travis/install-dependencies.sh
coveralls hasn't been including the branch info since we moved to travis-ci.com
=> Install cpp-coveralls from source to support service name

docker/travis/Dockerfile-opflex, docker/travis/Dockerfile-opflex-build-base, docker/travis/Dockerfile-opflexserver
ubi base image in 9.4 and latest uses openssl-libs-1:3.2.1-1.el9.x86_64 that conflicts with openssl-fips-provider-3.0.7-2.el9.x86_64 from mirror.stream.centos.org_9-stream_BaseOS_x86_64_os because the centos contains openssl-libs-3.2.1-1.el9.x86_64.rpm. we cannot remove the older version because systemd depends on it. So lock the version until its resolved in upstream
=> Lock ubi version to 9.3 to prevent conflicts

agent-ovs/lib/cmd.cpp, agent-ovs/ovs/AdvertManager.cpp, agent-ovs/ovs/FlowExecutor.cpp, agent-ovs/ovs/FlowReader.cpp, agent-ovs/ovs/InterfaceStatsManager.cpp, agent-ovs/ovs/NatStatsManager.cpp, agent-ovs/ovs/OvsdbConnection.cpp, agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/PolicyStatsManager.cpp, agent-ovs/ovs/PortMapper.cpp, agent-ovs/ovs/SwitchConnection.cpp, agent-ovs/ovs/ovs-shim.c, agent-ovs/ovs/test/ContractStatsManager_test.cpp
pkgconfig include path has changed in OVS 2.13.*+
We probably should have been referencing like this anyway
=> Update OVS lib includes

agent-ovs/lib/Agent.cpp, agent-ovs/lib/include/opflexagent/Agent.h, docker/travis/launch-opflexagent.sh, libopflex/engine/Processor.cpp, libopflex/engine/include/opflex/engine/Processor.h, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/ofcore/OFFramework.cpp
"opflex": {
"startup": {
"enabled": "true",
with default being false. If false none of the startup related code will be executed.
Also create a startup subdir ${VARDIR}/lib/opflex-agent-ovs/startup
=> Add enable config option for startup section

agent-ovs/debian/control
This was only needed in older ubuntu distros. In newer distros such as jammy, it causes build failures due to a missing dh-system dependency.
(cherry picked from commit 17199baa1425dfb4abec14461586d71573ffe283)
=> Remove dh-systemd (#491)

agent-ovs/ovs/include/PacketLogHandler.h, agent-ovs/ovs/test/PacketDecoder_test.cpp
Incorrect field was being used for ip prefixlen in prunefilter.
(cherry picked from commit 3d7cc7320312fd9a77740529afb8786208fa72c0)
=> Fix prefixlen matching in prunefilter

agent-ovs/Makefile.am, agent-ovs/cmd/mcast_daemon.cpp, agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/include/opflexagent/PolicyManager.h, agent-ovs/ovs/AccessFlowManager.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/PacketInHandler.cpp, agent-ovs/ovs/Packets.cpp, agent-ovs/ovs/QosRenderer.cpp, agent-ovs/ovs/SpanRenderer.cpp, agent-ovs/ovs/include/IntFlowManager.h, agent-ovs/ovs/include/NatStatsManager.h, agent-ovs/ovs/test/NetFlowRenderer_test.cpp, agent-ovs/server/opflex_server.cpp
(cherry picked from commit 37b5c9b5785eb83829696b6dafca8e0e907c6185)
=> Cleanup some more coverity complaints

agent-ovs/cmd/gbp_inspect.cpp, libopflex/engine/InspectorClientConn.cpp, libopflex/engine/InspectorClientImpl.cpp, libopflex/engine/include/opflex/engine/InspectorClientImpl.h, libopflex/engine/include/opflex/engine/internal/InspectorClientConn.h, libopflex/include/opflex/ofcore/InspectorClient.h, libopflex/ofcore/test/Inspector_test.cpp
The gbp_inspect utility currently uses a fixed timeout of 5 seconds for queries. This patch adds a parameter that allows users to set a different timeout for the query. The -i argument is used to pass the timeout value in milliseconds.
=> Make inspect timeout configurable

docker/rpms/Dockerfile-opflexrpm-build, docker/rpms/Dockerfile-opflexrpm-build-base, docker/rpms/README.txt, docker/rpms/build_opflex_baserpm.sh, docker/rpms/build_opflexrpm.sh
=> Add support for ubi8 rpmbuild

.travis/travis-build.sh, agent-ovs/lib/FSPacketDropLogConfigSource.cpp, agent-ovs/lib/test/ExtraConfigManager_test.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/include/PacketLogHandler.h
When src/dst prefix lengths were unset, fields
contained an empty space, which was inadvertently added while parsing for mask, which caused an
exception in opflex_agent
=> Fix exception with stoul for droppruning

agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/ovs/SwitchManager.cpp, agent-ovs/ovs/include/SwitchManager.h, agent-ovs/ovs/test/include/FlowManagerFixture.h, libopflex/engine/Processor.cpp
As an optimization turn off startup policy if the read fails for any reason or if 0 objects are read
Also switch sync delay may not be reliable if the config file that enables it is read after renderer config. Fix it by reading the value before using it (set in constructor)
=> disable startuppol on error, fix switch sync delay

agent-ovs/Makefile.am, agent-ovs/lib/PolicyManager.cpp, agent-ovs/lib/include/opflexagent/test/ModbFixture.h, agent-ovs/ovs/test/AccessFlowManager_LocalSG_test.cpp
- Basically a copy of AccessFlowManager_test.cpp and a %s replace to use LocalSecGroup and associated local objects and verify the resultant flows match what were seen before.
- only test deleted is the redirect action thats not implemented for local sec groups.
- In the process uncovered couple of issues
- uhandled LocalAllowDenyAction
- use a different string for task dispatch else if the secgrp dispatch processing is active it would skip the localsecgrps
=> Add UT for local-hpp and fix couple issues

agent-ovs/cmd/opflex_agent.cpp, agent-ovs/lib/Agent.cpp, agent-ovs/lib/EndpointManager.cpp, agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/opflex-agent-ovs.conf.in
There are 2 scenarios
1. reset.conf comes immediately after PlatformConfig delete We will skip processing it if within a certain time, 5 secs default This is so we do not trigger a disconnect twice for the same event, one via PlatformConfig delete and other via reset.conf
2. PlatformConfig delete comes after reset.conf This should not be an issue since we will not be able to get the PlatformConfig event once the connection has been reset via reset.conf processing. There is a small race here and in that worst case we may process the event twice but the window is significantly reduced.
=> Skip reset.conf if we processed PlatformConfig del

agent-ovs/Makefile.am, agent-ovs/lib/include/opflexagent/test/ModbFixture.h, agent-ovs/ovs/PolicyStatsManager.cpp, agent-ovs/ovs/SecGrpStatsManager.cpp, agent-ovs/ovs/include/SecGrpStatsManager.h, agent-ovs/ovs/test/ContractStatsManager_test.cpp, agent-ovs/ovs/test/SecGrpStatsManager_LocalSG_test.cpp, agent-ovs/ovs/test/include/PolicyStatsManagerFixture.h, genie/MODEL/EXTENSIONS/GBP/extensions.mdl
- added as an extension of SecGrpClassifierCounter
- added make checks as a copy of SecGrpStatsManager_test.cpp, replacing all the classifiers with Local, and convert the called functions to use template arguments.
- The make checks cover the prometheus tests
- this would also result in pushing the LocalSecGrpClassifierCounter to the leaf, should we decide to push the local secgrps to the leaf, we can strip the Local before sending it.
=> Add LocalSecGrpClassifierCounter

agent-ovs/Makefile.am, agent-ovs/lib/Agent.cpp, agent-ovs/lib/ExtraConfigManager.cpp, agent-ovs/lib/FSOutOfBandConfigSource.cpp, agent-ovs/lib/include/opflexagent/Agent.h, agent-ovs/lib/include/opflexagent/ExtraConfigListener.h, agent-ovs/lib/include/opflexagent/ExtraConfigManager.h, agent-ovs/lib/include/opflexagent/FSOutOfBandConfigSource.h, agent-ovs/lib/include/opflexagent/OutOfBandConfig.h, agent-ovs/lib/include/opflexagent/TunnelEpManager.h, agent-ovs/opflex-agent-ovs.conf.in, agent-ovs/ovs/AdvertManager.cpp, agent-ovs/ovs/IntFlowManager.cpp, agent-ovs/ovs/OVSRenderer.cpp, agent-ovs/ovs/include/AccessFlowManager.h, agent-ovs/ovs/include/AdvertManager.h, agent-ovs/ovs/include/EndpointTenantMapper.h, agent-ovs/ovs/include/IntFlowManager.h, agent-ovs/ovs/include/OVSRenderer.h, genie/MODEL/OWNERSHIP/own.mdl, genie/MODEL/SPECIFIC/OBSERVER/config.mdl, genie/MODEL/SPECIFIC/OBSERVER/universe.mdl
Change frequency of tunnel ep advertisement timer, based on out-of-band-config file inserted by host-agent.
=> Out of band config handling

docker/travis/launch-opflexagent.sh
--drop_log_file: to log packet drops to a different file that is available in $LOG_DIR of opflex-agent container
--drop_log_syslog: to log drops to syslog
=> Start opflex agent with extra args to specify drop-logs redirect

docker/travis/Dockerfile-opflex
vim-minimal-2:8.2.2637-20.el9_1 had security fixes and no longer available
The latest vim-minimal-8.2.2637-21.el9.x86_64.rpm      2024-08-07T17:19:45   690130
possibly has backports of those fixes. update to latest
=> Use latest version of vim

docker/travis/build-opflex-travis.sh
to only build opflex-build-base image
if a tag comtaining "opflex-build-base" is pushed
(cherry picked from commit 22be196f1dc1c7a62f94b4a10a9a612cb96358fe)
=> update opflex build

agent-ovs/lib/FSPacketDropLogConfigSource.cpp, agent-ovs/ovs/OVSRenderer.cpp
Although the value is limited to uint8.
Cast shouild be to int to convert correctly.
=> Fix incorrect conversion of prunefilter

.github/workflows/push-git-tag.yaml
added missing semicolon and corrected comment syntax
(cherry picked from commit ecc2c4516434885f31bf8f31cb74c25007b1eb8f)
=> Updated github workflow syntax

docker/travis/Dockerfile-opflex-build-base
and exclude openssl from updates to avoid
conflicting pkg versions
=> Pin openssl-devel to 3.2.2-6.el9_5.1

agent-ovs/lib/Agent.cpp, agent-ovs/lib/include/opflexagent/Agent.h, libopflex/engine/Processor.cpp, libopflex/engine/include/opflex/engine/Processor.h, libopflex/include/opflex/ofcore/OFFramework.h, libopflex/ofcore/OFFramework.cpp
When an existing EP is updated, instead of simply resending epdeclare, send a undeclare followed by declare.
The new behavior will be default unless disabled via flag.
Old (non default needs in opflex section)   "force-ep-undeclares": { "enabled" : "false" }
[2025-May-08 13:53:04.696491] [info] [lib/Agent.cpp:670:applyProperties] Setting force_ep_undeclares to 0
Update
[2025-May-08 13:53:34.708020] [debug] [Processor.cpp:433:declareObj] Declaring local endpoint /EprL3Universe/EprL3Ep/%2fPolicyUniverse%2fPolicySpace%2fcommon%2fGbpRoutingDomain%2frke-setup3-vrf%2f/10.2.0.204/ [2025-May-08 13:53:34.708752] [debug] [Processor.cpp:433:declareObj] Declaring local endpoint /EprL2Universe/EprL2Ep/%2fPolicyUniverse%2fPolicySpace%2frkesetup3%2fGbpBridgeDomain%2faci-containers-rkesetup3-pod-bd%2f/0a% …
=> Change EP declare behavior.

docker/travis/Dockerfile-opflex, docker/travis/Dockerfile-opflex-build-base, docker/travis/Dockerfile-opflexserver
Newer `openssl-libs` packages bundle the FIPS provider, which was previously a separate `openssl-fips-provider-so` package. This causes a file conflict during upgrades.
Work around this by removing the old FIPS provider package before upgrading to the new `openssl-libs`.
=> Handle OpenSSL FIPS provider package conflict

agent-ovs/lib/include/opflexagent/Agent.h, libopflex/engine/include/opflex/engine/Processor.h, libopflex/include/opflex/yajr/internal/comms.hpp, libopflex/include/opflex/yajr/yajr.hpp
The default timeout of the connect timer needed to be increased in order to support cases where the fabric is under load.
=> Change connect timer default timeout
